/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedStudiesIndexRouteImport } from './routes/_authenticated/studies/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedDataIndexRouteImport } from './routes/_authenticated/data/index'
import { Route as AuthenticatedApidocIndexRouteImport } from './routes/_authenticated/apidoc/index'
import { Route as AuthenticatedSettingsMaintenanceRouteImport } from './routes/_authenticated/settings/maintenance'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated/settings/general'
import { Route as AuthenticatedSettingsAboutRouteImport } from './routes/_authenticated/settings/about'
import { Route as AuthenticatedStudiesStudyIdRouteRouteImport } from './routes/_authenticated/studies/$studyId/route'
import { Route as AuthenticatedStudiesStudyIdIndexRouteImport } from './routes/_authenticated/studies/$studyId/index'
import { Route as AuthenticatedSettingsUsersIndexRouteImport } from './routes/_authenticated/settings/users/index'
import { Route as AuthenticatedSettingsTokensIndexRouteImport } from './routes/_authenticated/settings/tokens/index'
import { Route as AuthenticatedSettingsGroupsIndexRouteImport } from './routes/_authenticated/settings/groups/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudiesIndexRoute =
  AuthenticatedStudiesIndexRouteImport.update({
    id: '/studies/',
    path: '/studies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedDataIndexRoute = AuthenticatedDataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApidocIndexRoute =
  AuthenticatedApidocIndexRouteImport.update({
    id: '/apidoc/',
    path: '/apidoc/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsMaintenanceRoute =
  AuthenticatedSettingsMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAboutRoute =
  AuthenticatedSettingsAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdRouteRoute =
  AuthenticatedStudiesStudyIdRouteRouteImport.update({
    id: '/studies/$studyId',
    path: '/studies/$studyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdIndexRoute =
  AuthenticatedStudiesStudyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudiesStudyIdRouteRoute,
  } as any)
const AuthenticatedSettingsUsersIndexRoute =
  AuthenticatedSettingsUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsTokensIndexRoute =
  AuthenticatedSettingsTokensIndexRouteImport.update({
    id: '/tokens/',
    path: '/tokens/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsGroupsIndexRoute =
  AuthenticatedSettingsGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/studies/$studyId': typeof AuthenticatedStudiesStudyIdRouteRouteWithChildren
  '/settings/about': typeof AuthenticatedSettingsAboutRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/maintenance': typeof AuthenticatedSettingsMaintenanceRoute
  '/apidoc': typeof AuthenticatedApidocIndexRoute
  '/data': typeof AuthenticatedDataIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/studies': typeof AuthenticatedStudiesIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/settings/groups': typeof AuthenticatedSettingsGroupsIndexRoute
  '/settings/tokens': typeof AuthenticatedSettingsTokensIndexRoute
  '/settings/users': typeof AuthenticatedSettingsUsersIndexRoute
  '/studies/$studyId/': typeof AuthenticatedStudiesStudyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/settings/about': typeof AuthenticatedSettingsAboutRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/maintenance': typeof AuthenticatedSettingsMaintenanceRoute
  '/apidoc': typeof AuthenticatedApidocIndexRoute
  '/data': typeof AuthenticatedDataIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/studies': typeof AuthenticatedStudiesIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/settings/groups': typeof AuthenticatedSettingsGroupsIndexRoute
  '/settings/tokens': typeof AuthenticatedSettingsTokensIndexRoute
  '/settings/users': typeof AuthenticatedSettingsUsersIndexRoute
  '/studies/$studyId': typeof AuthenticatedStudiesStudyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/studies/$studyId': typeof AuthenticatedStudiesStudyIdRouteRouteWithChildren
  '/_authenticated/settings/about': typeof AuthenticatedSettingsAboutRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/maintenance': typeof AuthenticatedSettingsMaintenanceRoute
  '/_authenticated/apidoc/': typeof AuthenticatedApidocIndexRoute
  '/_authenticated/data/': typeof AuthenticatedDataIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/studies/': typeof AuthenticatedStudiesIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/settings/groups/': typeof AuthenticatedSettingsGroupsIndexRoute
  '/_authenticated/settings/tokens/': typeof AuthenticatedSettingsTokensIndexRoute
  '/_authenticated/settings/users/': typeof AuthenticatedSettingsUsersIndexRoute
  '/_authenticated/studies/$studyId/': typeof AuthenticatedStudiesStudyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/'
    | '/login'
    | '/studies/$studyId'
    | '/settings/about'
    | '/settings/general'
    | '/settings/maintenance'
    | '/apidoc'
    | '/data'
    | '/settings/'
    | '/studies'
    | '/tasks'
    | '/settings/groups'
    | '/settings/tokens'
    | '/settings/users'
    | '/studies/$studyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings/about'
    | '/settings/general'
    | '/settings/maintenance'
    | '/apidoc'
    | '/data'
    | '/settings'
    | '/studies'
    | '/tasks'
    | '/settings/groups'
    | '/settings/tokens'
    | '/settings/users'
    | '/studies/$studyId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/login/'
    | '/_authenticated/studies/$studyId'
    | '/_authenticated/settings/about'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/maintenance'
    | '/_authenticated/apidoc/'
    | '/_authenticated/data/'
    | '/_authenticated/settings/'
    | '/_authenticated/studies/'
    | '/_authenticated/tasks/'
    | '/_authenticated/settings/groups/'
    | '/_authenticated/settings/tokens/'
    | '/_authenticated/settings/users/'
    | '/_authenticated/studies/$studyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studies/': {
      id: '/_authenticated/studies/'
      path: '/studies'
      fullPath: '/studies'
      preLoaderRoute: typeof AuthenticatedStudiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/data/': {
      id: '/_authenticated/data/'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof AuthenticatedDataIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apidoc/': {
      id: '/_authenticated/apidoc/'
      path: '/apidoc'
      fullPath: '/apidoc'
      preLoaderRoute: typeof AuthenticatedApidocIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/maintenance': {
      id: '/_authenticated/settings/maintenance'
      path: '/maintenance'
      fullPath: '/settings/maintenance'
      preLoaderRoute: typeof AuthenticatedSettingsMaintenanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/about': {
      id: '/_authenticated/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof AuthenticatedSettingsAboutRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/studies/$studyId': {
      id: '/_authenticated/studies/$studyId'
      path: '/studies/$studyId'
      fullPath: '/studies/$studyId'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studies/$studyId/': {
      id: '/_authenticated/studies/$studyId/'
      path: '/'
      fullPath: '/studies/$studyId/'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdRouteRoute
    }
    '/_authenticated/settings/users/': {
      id: '/_authenticated/settings/users/'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/tokens/': {
      id: '/_authenticated/settings/tokens/'
      path: '/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof AuthenticatedSettingsTokensIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/groups/': {
      id: '/_authenticated/settings/groups/'
      path: '/groups'
      fullPath: '/settings/groups'
      preLoaderRoute: typeof AuthenticatedSettingsGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAboutRoute: typeof AuthenticatedSettingsAboutRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsMaintenanceRoute: typeof AuthenticatedSettingsMaintenanceRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsGroupsIndexRoute: typeof AuthenticatedSettingsGroupsIndexRoute
  AuthenticatedSettingsTokensIndexRoute: typeof AuthenticatedSettingsTokensIndexRoute
  AuthenticatedSettingsUsersIndexRoute: typeof AuthenticatedSettingsUsersIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAboutRoute: AuthenticatedSettingsAboutRoute,
    AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
    AuthenticatedSettingsMaintenanceRoute:
      AuthenticatedSettingsMaintenanceRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
    AuthenticatedSettingsGroupsIndexRoute:
      AuthenticatedSettingsGroupsIndexRoute,
    AuthenticatedSettingsTokensIndexRoute:
      AuthenticatedSettingsTokensIndexRoute,
    AuthenticatedSettingsUsersIndexRoute: AuthenticatedSettingsUsersIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedStudiesStudyIdRouteRouteChildren {
  AuthenticatedStudiesStudyIdIndexRoute: typeof AuthenticatedStudiesStudyIdIndexRoute
}

const AuthenticatedStudiesStudyIdRouteRouteChildren: AuthenticatedStudiesStudyIdRouteRouteChildren =
  {
    AuthenticatedStudiesStudyIdIndexRoute:
      AuthenticatedStudiesStudyIdIndexRoute,
  }

const AuthenticatedStudiesStudyIdRouteRouteWithChildren =
  AuthenticatedStudiesStudyIdRouteRoute._addFileChildren(
    AuthenticatedStudiesStudyIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedStudiesStudyIdRouteRoute: typeof AuthenticatedStudiesStudyIdRouteRouteWithChildren
  AuthenticatedApidocIndexRoute: typeof AuthenticatedApidocIndexRoute
  AuthenticatedDataIndexRoute: typeof AuthenticatedDataIndexRoute
  AuthenticatedStudiesIndexRoute: typeof AuthenticatedStudiesIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedStudiesStudyIdRouteRoute:
    AuthenticatedStudiesStudyIdRouteRouteWithChildren,
  AuthenticatedApidocIndexRoute: AuthenticatedApidocIndexRoute,
  AuthenticatedDataIndexRoute: AuthenticatedDataIndexRoute,
  AuthenticatedStudiesIndexRoute: AuthenticatedStudiesIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
