/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedStudiesIndexRouteImport } from './routes/_authenticated/studies/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedDataIndexRouteImport } from './routes/_authenticated/data/index'
import { Route as AuthenticatedApidocIndexRouteImport } from './routes/_authenticated/apidoc/index'
import { Route as AuthenticatedSettingsMaintenanceRouteImport } from './routes/_authenticated/settings/maintenance'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated/settings/general'
import { Route as AuthenticatedSettingsAboutRouteImport } from './routes/_authenticated/settings/about'
import { Route as AuthenticatedStudiesStudyIdRouteRouteImport } from './routes/_authenticated/studies/$studyId/route'
import { Route as AuthenticatedStudiesStudyIdIndexRouteImport } from './routes/_authenticated/studies/$studyId/index'
import { Route as AuthenticatedSettingsUsersIndexRouteImport } from './routes/_authenticated/settings/users/index'
import { Route as AuthenticatedSettingsTokensIndexRouteImport } from './routes/_authenticated/settings/tokens/index'
import { Route as AuthenticatedSettingsGroupsIndexRouteImport } from './routes/_authenticated/settings/groups/index'
import { Route as AuthenticatedStudiesStudyIdExploreRouteRouteImport } from './routes/_authenticated/studies/$studyId/explore/route'
import { Route as AuthenticatedStudiesStudyIdExploreIndexRouteImport } from './routes/_authenticated/studies/$studyId/explore/index'
import { Route as AuthenticatedStudiesStudyIdExploreXpansionRouteRouteImport } from './routes/_authenticated/studies/$studyId/explore/xpansion/route'
import { Route as AuthenticatedStudiesStudyIdExploreTablemodeRouteRouteImport } from './routes/_authenticated/studies/$studyId/explore/tablemode/route'
import { Route as AuthenticatedStudiesStudyIdExploreModelizationRouteRouteImport } from './routes/_authenticated/studies/$studyId/explore/modelization/route'
import { Route as AuthenticatedStudiesStudyIdExploreConfigurationRouteRouteImport } from './routes/_authenticated/studies/$studyId/explore/configuration/route'
import { Route as AuthenticatedStudiesStudyIdExploreXpansionIndexRouteImport } from './routes/_authenticated/studies/$studyId/explore/xpansion/index'
import { Route as AuthenticatedStudiesStudyIdExploreOutputsIndexRouteImport } from './routes/_authenticated/studies/$studyId/explore/outputs/index'
import { Route as AuthenticatedStudiesStudyIdExploreModelizationIndexRouteImport } from './routes/_authenticated/studies/$studyId/explore/modelization/index'
import { Route as AuthenticatedStudiesStudyIdExploreDebugIndexRouteImport } from './routes/_authenticated/studies/$studyId/explore/debug/index'
import { Route as AuthenticatedStudiesStudyIdExploreConfigurationIndexRouteImport } from './routes/_authenticated/studies/$studyId/explore/configuration/index'
import { Route as AuthenticatedStudiesStudyIdExploreXpansionWeightsRouteImport } from './routes/_authenticated/studies/$studyId/explore/xpansion/weights'
import { Route as AuthenticatedStudiesStudyIdExploreXpansionConstraintsRouteImport } from './routes/_authenticated/studies/$studyId/explore/xpansion/constraints'
import { Route as AuthenticatedStudiesStudyIdExploreXpansionCapacitiesRouteImport } from './routes/_authenticated/studies/$studyId/explore/xpansion/capacities'
import { Route as AuthenticatedStudiesStudyIdExploreConfigurationEcoOptionsRouteImport } from './routes/_authenticated/studies/$studyId/explore/configuration/eco-options'
import { Route as AuthenticatedStudiesStudyIdExploreModelizationAreasRouteRouteImport } from './routes/_authenticated/studies/$studyId/explore/modelization/areas/route'
import { Route as AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRouteImport } from './routes/_authenticated/studies/$studyId/explore/configuration/geo-trimming/route'
import { Route as AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchRouteRouteImport } from './routes/_authenticated/studies/$studyId/explore/configuration/adequacy-patch/route'
import { Route as AuthenticatedStudiesStudyIdExploreXpansionSettingsIndexRouteImport } from './routes/_authenticated/studies/$studyId/explore/xpansion/settings/index'
import { Route as AuthenticatedStudiesStudyIdExploreXpansionCandidatesIndexRouteImport } from './routes/_authenticated/studies/$studyId/explore/xpansion/candidates/index'
import { Route as AuthenticatedStudiesStudyIdExploreTablemodeTableModeIdIndexRouteImport } from './routes/_authenticated/studies/$studyId/explore/tablemode/$tableModeId/index'
import { Route as AuthenticatedStudiesStudyIdExploreOutputsOutputIdIndexRouteImport } from './routes/_authenticated/studies/$studyId/explore/outputs/$outputId/index'
import { Route as AuthenticatedStudiesStudyIdExploreModelizationMapIndexRouteImport } from './routes/_authenticated/studies/$studyId/explore/modelization/map/index'
import { Route as AuthenticatedStudiesStudyIdExploreConfigurationTsGenerationIndexRouteImport } from './routes/_authenticated/studies/$studyId/explore/configuration/ts-generation/index'
import { Route as AuthenticatedStudiesStudyIdExploreConfigurationOptimizationIndexRouteImport } from './routes/_authenticated/studies/$studyId/explore/configuration/optimization/index'
import { Route as AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingIndexRouteImport } from './routes/_authenticated/studies/$studyId/explore/configuration/geo-trimming/index'
import { Route as AuthenticatedStudiesStudyIdExploreConfigurationGeneralIndexRouteImport } from './routes/_authenticated/studies/$studyId/explore/configuration/general/index'
import { Route as AuthenticatedStudiesStudyIdExploreConfigurationAdvancedParamsIndexRouteImport } from './routes/_authenticated/studies/$studyId/explore/configuration/advanced-params/index'
import { Route as AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchIndexRouteImport } from './routes/_authenticated/studies/$studyId/explore/configuration/adequacy-patch/index'
import { Route as AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingLinksRouteImport } from './routes/_authenticated/studies/$studyId/explore/configuration/geo-trimming/links'
import { Route as AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingBindingConstraintsRouteImport } from './routes/_authenticated/studies/$studyId/explore/configuration/geo-trimming/binding-constraints'
import { Route as AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingAreasRouteImport } from './routes/_authenticated/studies/$studyId/explore/configuration/geo-trimming/areas'
import { Route as AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchPerimeterRouteImport } from './routes/_authenticated/studies/$studyId/explore/configuration/adequacy-patch/perimeter'
import { Route as AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRouteImport } from './routes/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/route'
import { Route as AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdIndexRouteImport } from './routes/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/index'
import { Route as AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchGeneralIndexRouteImport } from './routes/_authenticated/studies/$studyId/explore/configuration/adequacy-patch/general/index'
import { Route as AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdLoadRouteImport } from './routes/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/load'
import { Route as AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsIndexRouteImport } from './routes/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/index'
import { Route as AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdPropertiesIndexRouteImport } from './routes/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/properties/index'
import { Route as AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdRouteRouteImport } from './routes/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/route'
import { Route as AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdIndexRouteImport } from './routes/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/index'
import { Route as AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdParametersRouteImport } from './routes/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/parameters'
import { Route as AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdMatricesRouteImport } from './routes/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/matrices'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudiesIndexRoute =
  AuthenticatedStudiesIndexRouteImport.update({
    id: '/studies/',
    path: '/studies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedDataIndexRoute = AuthenticatedDataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApidocIndexRoute =
  AuthenticatedApidocIndexRouteImport.update({
    id: '/apidoc/',
    path: '/apidoc/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsMaintenanceRoute =
  AuthenticatedSettingsMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAboutRoute =
  AuthenticatedSettingsAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdRouteRoute =
  AuthenticatedStudiesStudyIdRouteRouteImport.update({
    id: '/studies/$studyId',
    path: '/studies/$studyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdIndexRoute =
  AuthenticatedStudiesStudyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudiesStudyIdRouteRoute,
  } as any)
const AuthenticatedSettingsUsersIndexRoute =
  AuthenticatedSettingsUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsTokensIndexRoute =
  AuthenticatedSettingsTokensIndexRouteImport.update({
    id: '/tokens/',
    path: '/tokens/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsGroupsIndexRoute =
  AuthenticatedSettingsGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdExploreRouteRoute =
  AuthenticatedStudiesStudyIdExploreRouteRouteImport.update({
    id: '/explore',
    path: '/explore',
    getParentRoute: () => AuthenticatedStudiesStudyIdRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdExploreIndexRoute =
  AuthenticatedStudiesStudyIdExploreIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudiesStudyIdExploreRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdExploreXpansionRouteRoute =
  AuthenticatedStudiesStudyIdExploreXpansionRouteRouteImport.update({
    id: '/xpansion',
    path: '/xpansion',
    getParentRoute: () => AuthenticatedStudiesStudyIdExploreRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdExploreTablemodeRouteRoute =
  AuthenticatedStudiesStudyIdExploreTablemodeRouteRouteImport.update({
    id: '/tablemode',
    path: '/tablemode',
    getParentRoute: () => AuthenticatedStudiesStudyIdExploreRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdExploreModelizationRouteRoute =
  AuthenticatedStudiesStudyIdExploreModelizationRouteRouteImport.update({
    id: '/modelization',
    path: '/modelization',
    getParentRoute: () => AuthenticatedStudiesStudyIdExploreRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdExploreConfigurationRouteRoute =
  AuthenticatedStudiesStudyIdExploreConfigurationRouteRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => AuthenticatedStudiesStudyIdExploreRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdExploreXpansionIndexRoute =
  AuthenticatedStudiesStudyIdExploreXpansionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudiesStudyIdExploreXpansionRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdExploreOutputsIndexRoute =
  AuthenticatedStudiesStudyIdExploreOutputsIndexRouteImport.update({
    id: '/outputs/',
    path: '/outputs/',
    getParentRoute: () => AuthenticatedStudiesStudyIdExploreRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdExploreModelizationIndexRoute =
  AuthenticatedStudiesStudyIdExploreModelizationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedStudiesStudyIdExploreModelizationRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdExploreDebugIndexRoute =
  AuthenticatedStudiesStudyIdExploreDebugIndexRouteImport.update({
    id: '/debug/',
    path: '/debug/',
    getParentRoute: () => AuthenticatedStudiesStudyIdExploreRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdExploreConfigurationIndexRoute =
  AuthenticatedStudiesStudyIdExploreConfigurationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedStudiesStudyIdExploreConfigurationRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdExploreXpansionWeightsRoute =
  AuthenticatedStudiesStudyIdExploreXpansionWeightsRouteImport.update({
    id: '/weights',
    path: '/weights',
    getParentRoute: () => AuthenticatedStudiesStudyIdExploreXpansionRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdExploreXpansionConstraintsRoute =
  AuthenticatedStudiesStudyIdExploreXpansionConstraintsRouteImport.update({
    id: '/constraints',
    path: '/constraints',
    getParentRoute: () => AuthenticatedStudiesStudyIdExploreXpansionRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdExploreXpansionCapacitiesRoute =
  AuthenticatedStudiesStudyIdExploreXpansionCapacitiesRouteImport.update({
    id: '/capacities',
    path: '/capacities',
    getParentRoute: () => AuthenticatedStudiesStudyIdExploreXpansionRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdExploreConfigurationEcoOptionsRoute =
  AuthenticatedStudiesStudyIdExploreConfigurationEcoOptionsRouteImport.update({
    id: '/eco-options',
    path: '/eco-options',
    getParentRoute: () =>
      AuthenticatedStudiesStudyIdExploreConfigurationRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdExploreModelizationAreasRouteRoute =
  AuthenticatedStudiesStudyIdExploreModelizationAreasRouteRouteImport.update({
    id: '/areas',
    path: '/areas',
    getParentRoute: () =>
      AuthenticatedStudiesStudyIdExploreModelizationRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRoute =
  AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRouteImport.update(
    {
      id: '/geo-trimming',
      path: '/geo-trimming',
      getParentRoute: () =>
        AuthenticatedStudiesStudyIdExploreConfigurationRouteRoute,
    } as any,
  )
const AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchRouteRoute =
  AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchRouteRouteImport.update(
    {
      id: '/adequacy-patch',
      path: '/adequacy-patch',
      getParentRoute: () =>
        AuthenticatedStudiesStudyIdExploreConfigurationRouteRoute,
    } as any,
  )
const AuthenticatedStudiesStudyIdExploreXpansionSettingsIndexRoute =
  AuthenticatedStudiesStudyIdExploreXpansionSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedStudiesStudyIdExploreXpansionRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdExploreXpansionCandidatesIndexRoute =
  AuthenticatedStudiesStudyIdExploreXpansionCandidatesIndexRouteImport.update({
    id: '/candidates/',
    path: '/candidates/',
    getParentRoute: () => AuthenticatedStudiesStudyIdExploreXpansionRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdExploreTablemodeTableModeIdIndexRoute =
  AuthenticatedStudiesStudyIdExploreTablemodeTableModeIdIndexRouteImport.update(
    {
      id: '/$tableModeId/',
      path: '/$tableModeId/',
      getParentRoute: () =>
        AuthenticatedStudiesStudyIdExploreTablemodeRouteRoute,
    } as any,
  )
const AuthenticatedStudiesStudyIdExploreOutputsOutputIdIndexRoute =
  AuthenticatedStudiesStudyIdExploreOutputsOutputIdIndexRouteImport.update({
    id: '/outputs/$outputId/',
    path: '/outputs/$outputId/',
    getParentRoute: () => AuthenticatedStudiesStudyIdExploreRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdExploreModelizationMapIndexRoute =
  AuthenticatedStudiesStudyIdExploreModelizationMapIndexRouteImport.update({
    id: '/map/',
    path: '/map/',
    getParentRoute: () =>
      AuthenticatedStudiesStudyIdExploreModelizationRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdExploreConfigurationTsGenerationIndexRoute =
  AuthenticatedStudiesStudyIdExploreConfigurationTsGenerationIndexRouteImport.update(
    {
      id: '/ts-generation/',
      path: '/ts-generation/',
      getParentRoute: () =>
        AuthenticatedStudiesStudyIdExploreConfigurationRouteRoute,
    } as any,
  )
const AuthenticatedStudiesStudyIdExploreConfigurationOptimizationIndexRoute =
  AuthenticatedStudiesStudyIdExploreConfigurationOptimizationIndexRouteImport.update(
    {
      id: '/optimization/',
      path: '/optimization/',
      getParentRoute: () =>
        AuthenticatedStudiesStudyIdExploreConfigurationRouteRoute,
    } as any,
  )
const AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingIndexRoute =
  AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRoute,
    } as any,
  )
const AuthenticatedStudiesStudyIdExploreConfigurationGeneralIndexRoute =
  AuthenticatedStudiesStudyIdExploreConfigurationGeneralIndexRouteImport.update(
    {
      id: '/general/',
      path: '/general/',
      getParentRoute: () =>
        AuthenticatedStudiesStudyIdExploreConfigurationRouteRoute,
    } as any,
  )
const AuthenticatedStudiesStudyIdExploreConfigurationAdvancedParamsIndexRoute =
  AuthenticatedStudiesStudyIdExploreConfigurationAdvancedParamsIndexRouteImport.update(
    {
      id: '/advanced-params/',
      path: '/advanced-params/',
      getParentRoute: () =>
        AuthenticatedStudiesStudyIdExploreConfigurationRouteRoute,
    } as any,
  )
const AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchIndexRoute =
  AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchRouteRoute,
    } as any,
  )
const AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingLinksRoute =
  AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingLinksRouteImport.update(
    {
      id: '/links',
      path: '/links',
      getParentRoute: () =>
        AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRoute,
    } as any,
  )
const AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingBindingConstraintsRoute =
  AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingBindingConstraintsRouteImport.update(
    {
      id: '/binding-constraints',
      path: '/binding-constraints',
      getParentRoute: () =>
        AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRoute,
    } as any,
  )
const AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingAreasRoute =
  AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingAreasRouteImport.update(
    {
      id: '/areas',
      path: '/areas',
      getParentRoute: () =>
        AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRoute,
    } as any,
  )
const AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchPerimeterRoute =
  AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchPerimeterRouteImport.update(
    {
      id: '/perimeter',
      path: '/perimeter',
      getParentRoute: () =>
        AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchRouteRoute,
    } as any,
  )
const AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRoute =
  AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRouteImport.update(
    {
      id: '/$areaId',
      path: '/$areaId',
      getParentRoute: () =>
        AuthenticatedStudiesStudyIdExploreModelizationAreasRouteRoute,
    } as any,
  )
const AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdIndexRoute =
  AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRoute,
    } as any,
  )
const AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchGeneralIndexRoute =
  AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchGeneralIndexRouteImport.update(
    {
      id: '/general/',
      path: '/general/',
      getParentRoute: () =>
        AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchRouteRoute,
    } as any,
  )
const AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdLoadRoute =
  AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdLoadRouteImport.update(
    {
      id: '/load',
      path: '/load',
      getParentRoute: () =>
        AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRoute,
    } as any,
  )
const AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsIndexRoute =
  AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsIndexRouteImport.update(
    {
      id: '/thermals/',
      path: '/thermals/',
      getParentRoute: () =>
        AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRoute,
    } as any,
  )
const AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdPropertiesIndexRoute =
  AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdPropertiesIndexRouteImport.update(
    {
      id: '/properties/',
      path: '/properties/',
      getParentRoute: () =>
        AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRoute,
    } as any,
  )
const AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdRouteRoute =
  AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdRouteRouteImport.update(
    {
      id: '/thermals/$thermalId',
      path: '/thermals/$thermalId',
      getParentRoute: () =>
        AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRoute,
    } as any,
  )
const AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdIndexRoute =
  AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdRouteRoute,
    } as any,
  )
const AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdParametersRoute =
  AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdParametersRouteImport.update(
    {
      id: '/parameters',
      path: '/parameters',
      getParentRoute: () =>
        AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdRouteRoute,
    } as any,
  )
const AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdMatricesRoute =
  AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdMatricesRouteImport.update(
    {
      id: '/matrices',
      path: '/matrices',
      getParentRoute: () =>
        AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/studies/$studyId': typeof AuthenticatedStudiesStudyIdRouteRouteWithChildren
  '/settings/about': typeof AuthenticatedSettingsAboutRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/maintenance': typeof AuthenticatedSettingsMaintenanceRoute
  '/apidoc': typeof AuthenticatedApidocIndexRoute
  '/data': typeof AuthenticatedDataIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/studies': typeof AuthenticatedStudiesIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/studies/$studyId/explore': typeof AuthenticatedStudiesStudyIdExploreRouteRouteWithChildren
  '/settings/groups': typeof AuthenticatedSettingsGroupsIndexRoute
  '/settings/tokens': typeof AuthenticatedSettingsTokensIndexRoute
  '/settings/users': typeof AuthenticatedSettingsUsersIndexRoute
  '/studies/$studyId/': typeof AuthenticatedStudiesStudyIdIndexRoute
  '/studies/$studyId/explore/configuration': typeof AuthenticatedStudiesStudyIdExploreConfigurationRouteRouteWithChildren
  '/studies/$studyId/explore/modelization': typeof AuthenticatedStudiesStudyIdExploreModelizationRouteRouteWithChildren
  '/studies/$studyId/explore/tablemode': typeof AuthenticatedStudiesStudyIdExploreTablemodeRouteRouteWithChildren
  '/studies/$studyId/explore/xpansion': typeof AuthenticatedStudiesStudyIdExploreXpansionRouteRouteWithChildren
  '/studies/$studyId/explore/': typeof AuthenticatedStudiesStudyIdExploreIndexRoute
  '/studies/$studyId/explore/configuration/adequacy-patch': typeof AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchRouteRouteWithChildren
  '/studies/$studyId/explore/configuration/geo-trimming': typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRouteWithChildren
  '/studies/$studyId/explore/modelization/areas': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasRouteRouteWithChildren
  '/studies/$studyId/explore/configuration/eco-options': typeof AuthenticatedStudiesStudyIdExploreConfigurationEcoOptionsRoute
  '/studies/$studyId/explore/xpansion/capacities': typeof AuthenticatedStudiesStudyIdExploreXpansionCapacitiesRoute
  '/studies/$studyId/explore/xpansion/constraints': typeof AuthenticatedStudiesStudyIdExploreXpansionConstraintsRoute
  '/studies/$studyId/explore/xpansion/weights': typeof AuthenticatedStudiesStudyIdExploreXpansionWeightsRoute
  '/studies/$studyId/explore/configuration/': typeof AuthenticatedStudiesStudyIdExploreConfigurationIndexRoute
  '/studies/$studyId/explore/debug': typeof AuthenticatedStudiesStudyIdExploreDebugIndexRoute
  '/studies/$studyId/explore/modelization/': typeof AuthenticatedStudiesStudyIdExploreModelizationIndexRoute
  '/studies/$studyId/explore/outputs': typeof AuthenticatedStudiesStudyIdExploreOutputsIndexRoute
  '/studies/$studyId/explore/xpansion/': typeof AuthenticatedStudiesStudyIdExploreXpansionIndexRoute
  '/studies/$studyId/explore/modelization/areas/$areaId': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRouteWithChildren
  '/studies/$studyId/explore/configuration/adequacy-patch/perimeter': typeof AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchPerimeterRoute
  '/studies/$studyId/explore/configuration/geo-trimming/areas': typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingAreasRoute
  '/studies/$studyId/explore/configuration/geo-trimming/binding-constraints': typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingBindingConstraintsRoute
  '/studies/$studyId/explore/configuration/geo-trimming/links': typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingLinksRoute
  '/studies/$studyId/explore/configuration/adequacy-patch/': typeof AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchIndexRoute
  '/studies/$studyId/explore/configuration/advanced-params': typeof AuthenticatedStudiesStudyIdExploreConfigurationAdvancedParamsIndexRoute
  '/studies/$studyId/explore/configuration/general': typeof AuthenticatedStudiesStudyIdExploreConfigurationGeneralIndexRoute
  '/studies/$studyId/explore/configuration/geo-trimming/': typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingIndexRoute
  '/studies/$studyId/explore/configuration/optimization': typeof AuthenticatedStudiesStudyIdExploreConfigurationOptimizationIndexRoute
  '/studies/$studyId/explore/configuration/ts-generation': typeof AuthenticatedStudiesStudyIdExploreConfigurationTsGenerationIndexRoute
  '/studies/$studyId/explore/modelization/map': typeof AuthenticatedStudiesStudyIdExploreModelizationMapIndexRoute
  '/studies/$studyId/explore/outputs/$outputId': typeof AuthenticatedStudiesStudyIdExploreOutputsOutputIdIndexRoute
  '/studies/$studyId/explore/tablemode/$tableModeId': typeof AuthenticatedStudiesStudyIdExploreTablemodeTableModeIdIndexRoute
  '/studies/$studyId/explore/xpansion/candidates': typeof AuthenticatedStudiesStudyIdExploreXpansionCandidatesIndexRoute
  '/studies/$studyId/explore/xpansion/settings': typeof AuthenticatedStudiesStudyIdExploreXpansionSettingsIndexRoute
  '/studies/$studyId/explore/modelization/areas/$areaId/load': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdLoadRoute
  '/studies/$studyId/explore/configuration/adequacy-patch/general': typeof AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchGeneralIndexRoute
  '/studies/$studyId/explore/modelization/areas/$areaId/': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdIndexRoute
  '/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdRouteRouteWithChildren
  '/studies/$studyId/explore/modelization/areas/$areaId/properties': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdPropertiesIndexRoute
  '/studies/$studyId/explore/modelization/areas/$areaId/thermals': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsIndexRoute
  '/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/matrices': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdMatricesRoute
  '/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/parameters': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdParametersRoute
  '/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/settings/about': typeof AuthenticatedSettingsAboutRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/maintenance': typeof AuthenticatedSettingsMaintenanceRoute
  '/apidoc': typeof AuthenticatedApidocIndexRoute
  '/data': typeof AuthenticatedDataIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/studies': typeof AuthenticatedStudiesIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/settings/groups': typeof AuthenticatedSettingsGroupsIndexRoute
  '/settings/tokens': typeof AuthenticatedSettingsTokensIndexRoute
  '/settings/users': typeof AuthenticatedSettingsUsersIndexRoute
  '/studies/$studyId': typeof AuthenticatedStudiesStudyIdIndexRoute
  '/studies/$studyId/explore/tablemode': typeof AuthenticatedStudiesStudyIdExploreTablemodeRouteRouteWithChildren
  '/studies/$studyId/explore': typeof AuthenticatedStudiesStudyIdExploreIndexRoute
  '/studies/$studyId/explore/modelization/areas': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasRouteRouteWithChildren
  '/studies/$studyId/explore/configuration/eco-options': typeof AuthenticatedStudiesStudyIdExploreConfigurationEcoOptionsRoute
  '/studies/$studyId/explore/xpansion/capacities': typeof AuthenticatedStudiesStudyIdExploreXpansionCapacitiesRoute
  '/studies/$studyId/explore/xpansion/constraints': typeof AuthenticatedStudiesStudyIdExploreXpansionConstraintsRoute
  '/studies/$studyId/explore/xpansion/weights': typeof AuthenticatedStudiesStudyIdExploreXpansionWeightsRoute
  '/studies/$studyId/explore/configuration': typeof AuthenticatedStudiesStudyIdExploreConfigurationIndexRoute
  '/studies/$studyId/explore/debug': typeof AuthenticatedStudiesStudyIdExploreDebugIndexRoute
  '/studies/$studyId/explore/modelization': typeof AuthenticatedStudiesStudyIdExploreModelizationIndexRoute
  '/studies/$studyId/explore/outputs': typeof AuthenticatedStudiesStudyIdExploreOutputsIndexRoute
  '/studies/$studyId/explore/xpansion': typeof AuthenticatedStudiesStudyIdExploreXpansionIndexRoute
  '/studies/$studyId/explore/configuration/adequacy-patch/perimeter': typeof AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchPerimeterRoute
  '/studies/$studyId/explore/configuration/geo-trimming/areas': typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingAreasRoute
  '/studies/$studyId/explore/configuration/geo-trimming/binding-constraints': typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingBindingConstraintsRoute
  '/studies/$studyId/explore/configuration/geo-trimming/links': typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingLinksRoute
  '/studies/$studyId/explore/configuration/adequacy-patch': typeof AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchIndexRoute
  '/studies/$studyId/explore/configuration/advanced-params': typeof AuthenticatedStudiesStudyIdExploreConfigurationAdvancedParamsIndexRoute
  '/studies/$studyId/explore/configuration/general': typeof AuthenticatedStudiesStudyIdExploreConfigurationGeneralIndexRoute
  '/studies/$studyId/explore/configuration/geo-trimming': typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingIndexRoute
  '/studies/$studyId/explore/configuration/optimization': typeof AuthenticatedStudiesStudyIdExploreConfigurationOptimizationIndexRoute
  '/studies/$studyId/explore/configuration/ts-generation': typeof AuthenticatedStudiesStudyIdExploreConfigurationTsGenerationIndexRoute
  '/studies/$studyId/explore/modelization/map': typeof AuthenticatedStudiesStudyIdExploreModelizationMapIndexRoute
  '/studies/$studyId/explore/outputs/$outputId': typeof AuthenticatedStudiesStudyIdExploreOutputsOutputIdIndexRoute
  '/studies/$studyId/explore/tablemode/$tableModeId': typeof AuthenticatedStudiesStudyIdExploreTablemodeTableModeIdIndexRoute
  '/studies/$studyId/explore/xpansion/candidates': typeof AuthenticatedStudiesStudyIdExploreXpansionCandidatesIndexRoute
  '/studies/$studyId/explore/xpansion/settings': typeof AuthenticatedStudiesStudyIdExploreXpansionSettingsIndexRoute
  '/studies/$studyId/explore/modelization/areas/$areaId/load': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdLoadRoute
  '/studies/$studyId/explore/configuration/adequacy-patch/general': typeof AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchGeneralIndexRoute
  '/studies/$studyId/explore/modelization/areas/$areaId': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdIndexRoute
  '/studies/$studyId/explore/modelization/areas/$areaId/properties': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdPropertiesIndexRoute
  '/studies/$studyId/explore/modelization/areas/$areaId/thermals': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsIndexRoute
  '/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/matrices': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdMatricesRoute
  '/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/parameters': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdParametersRoute
  '/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/studies/$studyId': typeof AuthenticatedStudiesStudyIdRouteRouteWithChildren
  '/_authenticated/settings/about': typeof AuthenticatedSettingsAboutRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/maintenance': typeof AuthenticatedSettingsMaintenanceRoute
  '/_authenticated/apidoc/': typeof AuthenticatedApidocIndexRoute
  '/_authenticated/data/': typeof AuthenticatedDataIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/studies/': typeof AuthenticatedStudiesIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/studies/$studyId/explore': typeof AuthenticatedStudiesStudyIdExploreRouteRouteWithChildren
  '/_authenticated/settings/groups/': typeof AuthenticatedSettingsGroupsIndexRoute
  '/_authenticated/settings/tokens/': typeof AuthenticatedSettingsTokensIndexRoute
  '/_authenticated/settings/users/': typeof AuthenticatedSettingsUsersIndexRoute
  '/_authenticated/studies/$studyId/': typeof AuthenticatedStudiesStudyIdIndexRoute
  '/_authenticated/studies/$studyId/explore/configuration': typeof AuthenticatedStudiesStudyIdExploreConfigurationRouteRouteWithChildren
  '/_authenticated/studies/$studyId/explore/modelization': typeof AuthenticatedStudiesStudyIdExploreModelizationRouteRouteWithChildren
  '/_authenticated/studies/$studyId/explore/tablemode': typeof AuthenticatedStudiesStudyIdExploreTablemodeRouteRouteWithChildren
  '/_authenticated/studies/$studyId/explore/xpansion': typeof AuthenticatedStudiesStudyIdExploreXpansionRouteRouteWithChildren
  '/_authenticated/studies/$studyId/explore/': typeof AuthenticatedStudiesStudyIdExploreIndexRoute
  '/_authenticated/studies/$studyId/explore/configuration/adequacy-patch': typeof AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchRouteRouteWithChildren
  '/_authenticated/studies/$studyId/explore/configuration/geo-trimming': typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRouteWithChildren
  '/_authenticated/studies/$studyId/explore/modelization/areas': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasRouteRouteWithChildren
  '/_authenticated/studies/$studyId/explore/configuration/eco-options': typeof AuthenticatedStudiesStudyIdExploreConfigurationEcoOptionsRoute
  '/_authenticated/studies/$studyId/explore/xpansion/capacities': typeof AuthenticatedStudiesStudyIdExploreXpansionCapacitiesRoute
  '/_authenticated/studies/$studyId/explore/xpansion/constraints': typeof AuthenticatedStudiesStudyIdExploreXpansionConstraintsRoute
  '/_authenticated/studies/$studyId/explore/xpansion/weights': typeof AuthenticatedStudiesStudyIdExploreXpansionWeightsRoute
  '/_authenticated/studies/$studyId/explore/configuration/': typeof AuthenticatedStudiesStudyIdExploreConfigurationIndexRoute
  '/_authenticated/studies/$studyId/explore/debug/': typeof AuthenticatedStudiesStudyIdExploreDebugIndexRoute
  '/_authenticated/studies/$studyId/explore/modelization/': typeof AuthenticatedStudiesStudyIdExploreModelizationIndexRoute
  '/_authenticated/studies/$studyId/explore/outputs/': typeof AuthenticatedStudiesStudyIdExploreOutputsIndexRoute
  '/_authenticated/studies/$studyId/explore/xpansion/': typeof AuthenticatedStudiesStudyIdExploreXpansionIndexRoute
  '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRouteWithChildren
  '/_authenticated/studies/$studyId/explore/configuration/adequacy-patch/perimeter': typeof AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchPerimeterRoute
  '/_authenticated/studies/$studyId/explore/configuration/geo-trimming/areas': typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingAreasRoute
  '/_authenticated/studies/$studyId/explore/configuration/geo-trimming/binding-constraints': typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingBindingConstraintsRoute
  '/_authenticated/studies/$studyId/explore/configuration/geo-trimming/links': typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingLinksRoute
  '/_authenticated/studies/$studyId/explore/configuration/adequacy-patch/': typeof AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchIndexRoute
  '/_authenticated/studies/$studyId/explore/configuration/advanced-params/': typeof AuthenticatedStudiesStudyIdExploreConfigurationAdvancedParamsIndexRoute
  '/_authenticated/studies/$studyId/explore/configuration/general/': typeof AuthenticatedStudiesStudyIdExploreConfigurationGeneralIndexRoute
  '/_authenticated/studies/$studyId/explore/configuration/geo-trimming/': typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingIndexRoute
  '/_authenticated/studies/$studyId/explore/configuration/optimization/': typeof AuthenticatedStudiesStudyIdExploreConfigurationOptimizationIndexRoute
  '/_authenticated/studies/$studyId/explore/configuration/ts-generation/': typeof AuthenticatedStudiesStudyIdExploreConfigurationTsGenerationIndexRoute
  '/_authenticated/studies/$studyId/explore/modelization/map/': typeof AuthenticatedStudiesStudyIdExploreModelizationMapIndexRoute
  '/_authenticated/studies/$studyId/explore/outputs/$outputId/': typeof AuthenticatedStudiesStudyIdExploreOutputsOutputIdIndexRoute
  '/_authenticated/studies/$studyId/explore/tablemode/$tableModeId/': typeof AuthenticatedStudiesStudyIdExploreTablemodeTableModeIdIndexRoute
  '/_authenticated/studies/$studyId/explore/xpansion/candidates/': typeof AuthenticatedStudiesStudyIdExploreXpansionCandidatesIndexRoute
  '/_authenticated/studies/$studyId/explore/xpansion/settings/': typeof AuthenticatedStudiesStudyIdExploreXpansionSettingsIndexRoute
  '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/load': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdLoadRoute
  '/_authenticated/studies/$studyId/explore/configuration/adequacy-patch/general/': typeof AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchGeneralIndexRoute
  '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdIndexRoute
  '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdRouteRouteWithChildren
  '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/properties/': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdPropertiesIndexRoute
  '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsIndexRoute
  '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/matrices': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdMatricesRoute
  '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/parameters': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdParametersRoute
  '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/': typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/'
    | '/login'
    | '/studies/$studyId'
    | '/settings/about'
    | '/settings/general'
    | '/settings/maintenance'
    | '/apidoc'
    | '/data'
    | '/settings/'
    | '/studies'
    | '/tasks'
    | '/studies/$studyId/explore'
    | '/settings/groups'
    | '/settings/tokens'
    | '/settings/users'
    | '/studies/$studyId/'
    | '/studies/$studyId/explore/configuration'
    | '/studies/$studyId/explore/modelization'
    | '/studies/$studyId/explore/tablemode'
    | '/studies/$studyId/explore/xpansion'
    | '/studies/$studyId/explore/'
    | '/studies/$studyId/explore/configuration/adequacy-patch'
    | '/studies/$studyId/explore/configuration/geo-trimming'
    | '/studies/$studyId/explore/modelization/areas'
    | '/studies/$studyId/explore/configuration/eco-options'
    | '/studies/$studyId/explore/xpansion/capacities'
    | '/studies/$studyId/explore/xpansion/constraints'
    | '/studies/$studyId/explore/xpansion/weights'
    | '/studies/$studyId/explore/configuration/'
    | '/studies/$studyId/explore/debug'
    | '/studies/$studyId/explore/modelization/'
    | '/studies/$studyId/explore/outputs'
    | '/studies/$studyId/explore/xpansion/'
    | '/studies/$studyId/explore/modelization/areas/$areaId'
    | '/studies/$studyId/explore/configuration/adequacy-patch/perimeter'
    | '/studies/$studyId/explore/configuration/geo-trimming/areas'
    | '/studies/$studyId/explore/configuration/geo-trimming/binding-constraints'
    | '/studies/$studyId/explore/configuration/geo-trimming/links'
    | '/studies/$studyId/explore/configuration/adequacy-patch/'
    | '/studies/$studyId/explore/configuration/advanced-params'
    | '/studies/$studyId/explore/configuration/general'
    | '/studies/$studyId/explore/configuration/geo-trimming/'
    | '/studies/$studyId/explore/configuration/optimization'
    | '/studies/$studyId/explore/configuration/ts-generation'
    | '/studies/$studyId/explore/modelization/map'
    | '/studies/$studyId/explore/outputs/$outputId'
    | '/studies/$studyId/explore/tablemode/$tableModeId'
    | '/studies/$studyId/explore/xpansion/candidates'
    | '/studies/$studyId/explore/xpansion/settings'
    | '/studies/$studyId/explore/modelization/areas/$areaId/load'
    | '/studies/$studyId/explore/configuration/adequacy-patch/general'
    | '/studies/$studyId/explore/modelization/areas/$areaId/'
    | '/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId'
    | '/studies/$studyId/explore/modelization/areas/$areaId/properties'
    | '/studies/$studyId/explore/modelization/areas/$areaId/thermals'
    | '/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/matrices'
    | '/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/parameters'
    | '/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings/about'
    | '/settings/general'
    | '/settings/maintenance'
    | '/apidoc'
    | '/data'
    | '/settings'
    | '/studies'
    | '/tasks'
    | '/settings/groups'
    | '/settings/tokens'
    | '/settings/users'
    | '/studies/$studyId'
    | '/studies/$studyId/explore/tablemode'
    | '/studies/$studyId/explore'
    | '/studies/$studyId/explore/modelization/areas'
    | '/studies/$studyId/explore/configuration/eco-options'
    | '/studies/$studyId/explore/xpansion/capacities'
    | '/studies/$studyId/explore/xpansion/constraints'
    | '/studies/$studyId/explore/xpansion/weights'
    | '/studies/$studyId/explore/configuration'
    | '/studies/$studyId/explore/debug'
    | '/studies/$studyId/explore/modelization'
    | '/studies/$studyId/explore/outputs'
    | '/studies/$studyId/explore/xpansion'
    | '/studies/$studyId/explore/configuration/adequacy-patch/perimeter'
    | '/studies/$studyId/explore/configuration/geo-trimming/areas'
    | '/studies/$studyId/explore/configuration/geo-trimming/binding-constraints'
    | '/studies/$studyId/explore/configuration/geo-trimming/links'
    | '/studies/$studyId/explore/configuration/adequacy-patch'
    | '/studies/$studyId/explore/configuration/advanced-params'
    | '/studies/$studyId/explore/configuration/general'
    | '/studies/$studyId/explore/configuration/geo-trimming'
    | '/studies/$studyId/explore/configuration/optimization'
    | '/studies/$studyId/explore/configuration/ts-generation'
    | '/studies/$studyId/explore/modelization/map'
    | '/studies/$studyId/explore/outputs/$outputId'
    | '/studies/$studyId/explore/tablemode/$tableModeId'
    | '/studies/$studyId/explore/xpansion/candidates'
    | '/studies/$studyId/explore/xpansion/settings'
    | '/studies/$studyId/explore/modelization/areas/$areaId/load'
    | '/studies/$studyId/explore/configuration/adequacy-patch/general'
    | '/studies/$studyId/explore/modelization/areas/$areaId'
    | '/studies/$studyId/explore/modelization/areas/$areaId/properties'
    | '/studies/$studyId/explore/modelization/areas/$areaId/thermals'
    | '/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/matrices'
    | '/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/parameters'
    | '/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/login/'
    | '/_authenticated/studies/$studyId'
    | '/_authenticated/settings/about'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/maintenance'
    | '/_authenticated/apidoc/'
    | '/_authenticated/data/'
    | '/_authenticated/settings/'
    | '/_authenticated/studies/'
    | '/_authenticated/tasks/'
    | '/_authenticated/studies/$studyId/explore'
    | '/_authenticated/settings/groups/'
    | '/_authenticated/settings/tokens/'
    | '/_authenticated/settings/users/'
    | '/_authenticated/studies/$studyId/'
    | '/_authenticated/studies/$studyId/explore/configuration'
    | '/_authenticated/studies/$studyId/explore/modelization'
    | '/_authenticated/studies/$studyId/explore/tablemode'
    | '/_authenticated/studies/$studyId/explore/xpansion'
    | '/_authenticated/studies/$studyId/explore/'
    | '/_authenticated/studies/$studyId/explore/configuration/adequacy-patch'
    | '/_authenticated/studies/$studyId/explore/configuration/geo-trimming'
    | '/_authenticated/studies/$studyId/explore/modelization/areas'
    | '/_authenticated/studies/$studyId/explore/configuration/eco-options'
    | '/_authenticated/studies/$studyId/explore/xpansion/capacities'
    | '/_authenticated/studies/$studyId/explore/xpansion/constraints'
    | '/_authenticated/studies/$studyId/explore/xpansion/weights'
    | '/_authenticated/studies/$studyId/explore/configuration/'
    | '/_authenticated/studies/$studyId/explore/debug/'
    | '/_authenticated/studies/$studyId/explore/modelization/'
    | '/_authenticated/studies/$studyId/explore/outputs/'
    | '/_authenticated/studies/$studyId/explore/xpansion/'
    | '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId'
    | '/_authenticated/studies/$studyId/explore/configuration/adequacy-patch/perimeter'
    | '/_authenticated/studies/$studyId/explore/configuration/geo-trimming/areas'
    | '/_authenticated/studies/$studyId/explore/configuration/geo-trimming/binding-constraints'
    | '/_authenticated/studies/$studyId/explore/configuration/geo-trimming/links'
    | '/_authenticated/studies/$studyId/explore/configuration/adequacy-patch/'
    | '/_authenticated/studies/$studyId/explore/configuration/advanced-params/'
    | '/_authenticated/studies/$studyId/explore/configuration/general/'
    | '/_authenticated/studies/$studyId/explore/configuration/geo-trimming/'
    | '/_authenticated/studies/$studyId/explore/configuration/optimization/'
    | '/_authenticated/studies/$studyId/explore/configuration/ts-generation/'
    | '/_authenticated/studies/$studyId/explore/modelization/map/'
    | '/_authenticated/studies/$studyId/explore/outputs/$outputId/'
    | '/_authenticated/studies/$studyId/explore/tablemode/$tableModeId/'
    | '/_authenticated/studies/$studyId/explore/xpansion/candidates/'
    | '/_authenticated/studies/$studyId/explore/xpansion/settings/'
    | '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/load'
    | '/_authenticated/studies/$studyId/explore/configuration/adequacy-patch/general/'
    | '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/'
    | '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId'
    | '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/properties/'
    | '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/'
    | '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/matrices'
    | '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/parameters'
    | '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studies/': {
      id: '/_authenticated/studies/'
      path: '/studies'
      fullPath: '/studies'
      preLoaderRoute: typeof AuthenticatedStudiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/data/': {
      id: '/_authenticated/data/'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof AuthenticatedDataIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apidoc/': {
      id: '/_authenticated/apidoc/'
      path: '/apidoc'
      fullPath: '/apidoc'
      preLoaderRoute: typeof AuthenticatedApidocIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/maintenance': {
      id: '/_authenticated/settings/maintenance'
      path: '/maintenance'
      fullPath: '/settings/maintenance'
      preLoaderRoute: typeof AuthenticatedSettingsMaintenanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/about': {
      id: '/_authenticated/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof AuthenticatedSettingsAboutRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/studies/$studyId': {
      id: '/_authenticated/studies/$studyId'
      path: '/studies/$studyId'
      fullPath: '/studies/$studyId'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studies/$studyId/': {
      id: '/_authenticated/studies/$studyId/'
      path: '/'
      fullPath: '/studies/$studyId/'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdRouteRoute
    }
    '/_authenticated/settings/users/': {
      id: '/_authenticated/settings/users/'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/tokens/': {
      id: '/_authenticated/settings/tokens/'
      path: '/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof AuthenticatedSettingsTokensIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/groups/': {
      id: '/_authenticated/settings/groups/'
      path: '/groups'
      fullPath: '/settings/groups'
      preLoaderRoute: typeof AuthenticatedSettingsGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/studies/$studyId/explore': {
      id: '/_authenticated/studies/$studyId/explore'
      path: '/explore'
      fullPath: '/studies/$studyId/explore'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreRouteRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/': {
      id: '/_authenticated/studies/$studyId/explore/'
      path: '/'
      fullPath: '/studies/$studyId/explore/'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/xpansion': {
      id: '/_authenticated/studies/$studyId/explore/xpansion'
      path: '/xpansion'
      fullPath: '/studies/$studyId/explore/xpansion'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreXpansionRouteRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/tablemode': {
      id: '/_authenticated/studies/$studyId/explore/tablemode'
      path: '/tablemode'
      fullPath: '/studies/$studyId/explore/tablemode'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreTablemodeRouteRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/modelization': {
      id: '/_authenticated/studies/$studyId/explore/modelization'
      path: '/modelization'
      fullPath: '/studies/$studyId/explore/modelization'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationRouteRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/configuration': {
      id: '/_authenticated/studies/$studyId/explore/configuration'
      path: '/configuration'
      fullPath: '/studies/$studyId/explore/configuration'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationRouteRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/xpansion/': {
      id: '/_authenticated/studies/$studyId/explore/xpansion/'
      path: '/'
      fullPath: '/studies/$studyId/explore/xpansion/'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreXpansionIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreXpansionRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/outputs/': {
      id: '/_authenticated/studies/$studyId/explore/outputs/'
      path: '/outputs'
      fullPath: '/studies/$studyId/explore/outputs'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreOutputsIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/modelization/': {
      id: '/_authenticated/studies/$studyId/explore/modelization/'
      path: '/'
      fullPath: '/studies/$studyId/explore/modelization/'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/debug/': {
      id: '/_authenticated/studies/$studyId/explore/debug/'
      path: '/debug'
      fullPath: '/studies/$studyId/explore/debug'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreDebugIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/configuration/': {
      id: '/_authenticated/studies/$studyId/explore/configuration/'
      path: '/'
      fullPath: '/studies/$studyId/explore/configuration/'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/xpansion/weights': {
      id: '/_authenticated/studies/$studyId/explore/xpansion/weights'
      path: '/weights'
      fullPath: '/studies/$studyId/explore/xpansion/weights'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreXpansionWeightsRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreXpansionRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/xpansion/constraints': {
      id: '/_authenticated/studies/$studyId/explore/xpansion/constraints'
      path: '/constraints'
      fullPath: '/studies/$studyId/explore/xpansion/constraints'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreXpansionConstraintsRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreXpansionRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/xpansion/capacities': {
      id: '/_authenticated/studies/$studyId/explore/xpansion/capacities'
      path: '/capacities'
      fullPath: '/studies/$studyId/explore/xpansion/capacities'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreXpansionCapacitiesRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreXpansionRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/configuration/eco-options': {
      id: '/_authenticated/studies/$studyId/explore/configuration/eco-options'
      path: '/eco-options'
      fullPath: '/studies/$studyId/explore/configuration/eco-options'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationEcoOptionsRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/modelization/areas': {
      id: '/_authenticated/studies/$studyId/explore/modelization/areas'
      path: '/areas'
      fullPath: '/studies/$studyId/explore/modelization/areas'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasRouteRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/configuration/geo-trimming': {
      id: '/_authenticated/studies/$studyId/explore/configuration/geo-trimming'
      path: '/geo-trimming'
      fullPath: '/studies/$studyId/explore/configuration/geo-trimming'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/configuration/adequacy-patch': {
      id: '/_authenticated/studies/$studyId/explore/configuration/adequacy-patch'
      path: '/adequacy-patch'
      fullPath: '/studies/$studyId/explore/configuration/adequacy-patch'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchRouteRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/xpansion/settings/': {
      id: '/_authenticated/studies/$studyId/explore/xpansion/settings/'
      path: '/settings'
      fullPath: '/studies/$studyId/explore/xpansion/settings'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreXpansionSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreXpansionRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/xpansion/candidates/': {
      id: '/_authenticated/studies/$studyId/explore/xpansion/candidates/'
      path: '/candidates'
      fullPath: '/studies/$studyId/explore/xpansion/candidates'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreXpansionCandidatesIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreXpansionRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/tablemode/$tableModeId/': {
      id: '/_authenticated/studies/$studyId/explore/tablemode/$tableModeId/'
      path: '/$tableModeId'
      fullPath: '/studies/$studyId/explore/tablemode/$tableModeId'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreTablemodeTableModeIdIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreTablemodeRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/outputs/$outputId/': {
      id: '/_authenticated/studies/$studyId/explore/outputs/$outputId/'
      path: '/outputs/$outputId'
      fullPath: '/studies/$studyId/explore/outputs/$outputId'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreOutputsOutputIdIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/modelization/map/': {
      id: '/_authenticated/studies/$studyId/explore/modelization/map/'
      path: '/map'
      fullPath: '/studies/$studyId/explore/modelization/map'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationMapIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/configuration/ts-generation/': {
      id: '/_authenticated/studies/$studyId/explore/configuration/ts-generation/'
      path: '/ts-generation'
      fullPath: '/studies/$studyId/explore/configuration/ts-generation'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationTsGenerationIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/configuration/optimization/': {
      id: '/_authenticated/studies/$studyId/explore/configuration/optimization/'
      path: '/optimization'
      fullPath: '/studies/$studyId/explore/configuration/optimization'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationOptimizationIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/configuration/geo-trimming/': {
      id: '/_authenticated/studies/$studyId/explore/configuration/geo-trimming/'
      path: '/'
      fullPath: '/studies/$studyId/explore/configuration/geo-trimming/'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/configuration/general/': {
      id: '/_authenticated/studies/$studyId/explore/configuration/general/'
      path: '/general'
      fullPath: '/studies/$studyId/explore/configuration/general'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationGeneralIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/configuration/advanced-params/': {
      id: '/_authenticated/studies/$studyId/explore/configuration/advanced-params/'
      path: '/advanced-params'
      fullPath: '/studies/$studyId/explore/configuration/advanced-params'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationAdvancedParamsIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/configuration/adequacy-patch/': {
      id: '/_authenticated/studies/$studyId/explore/configuration/adequacy-patch/'
      path: '/'
      fullPath: '/studies/$studyId/explore/configuration/adequacy-patch/'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/configuration/geo-trimming/links': {
      id: '/_authenticated/studies/$studyId/explore/configuration/geo-trimming/links'
      path: '/links'
      fullPath: '/studies/$studyId/explore/configuration/geo-trimming/links'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingLinksRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/configuration/geo-trimming/binding-constraints': {
      id: '/_authenticated/studies/$studyId/explore/configuration/geo-trimming/binding-constraints'
      path: '/binding-constraints'
      fullPath: '/studies/$studyId/explore/configuration/geo-trimming/binding-constraints'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingBindingConstraintsRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/configuration/geo-trimming/areas': {
      id: '/_authenticated/studies/$studyId/explore/configuration/geo-trimming/areas'
      path: '/areas'
      fullPath: '/studies/$studyId/explore/configuration/geo-trimming/areas'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingAreasRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/configuration/adequacy-patch/perimeter': {
      id: '/_authenticated/studies/$studyId/explore/configuration/adequacy-patch/perimeter'
      path: '/perimeter'
      fullPath: '/studies/$studyId/explore/configuration/adequacy-patch/perimeter'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchPerimeterRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId': {
      id: '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId'
      path: '/$areaId'
      fullPath: '/studies/$studyId/explore/modelization/areas/$areaId'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/': {
      id: '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/'
      path: '/'
      fullPath: '/studies/$studyId/explore/modelization/areas/$areaId/'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/configuration/adequacy-patch/general/': {
      id: '/_authenticated/studies/$studyId/explore/configuration/adequacy-patch/general/'
      path: '/general'
      fullPath: '/studies/$studyId/explore/configuration/adequacy-patch/general'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchGeneralIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/load': {
      id: '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/load'
      path: '/load'
      fullPath: '/studies/$studyId/explore/modelization/areas/$areaId/load'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdLoadRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/': {
      id: '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/'
      path: '/thermals'
      fullPath: '/studies/$studyId/explore/modelization/areas/$areaId/thermals'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/properties/': {
      id: '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/properties/'
      path: '/properties'
      fullPath: '/studies/$studyId/explore/modelization/areas/$areaId/properties'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId': {
      id: '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId'
      path: '/thermals/$thermalId'
      fullPath: '/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdRouteRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/': {
      id: '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/'
      path: '/'
      fullPath: '/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdIndexRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/parameters': {
      id: '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/parameters'
      path: '/parameters'
      fullPath: '/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/parameters'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdParametersRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdRouteRoute
    }
    '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/matrices': {
      id: '/_authenticated/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/matrices'
      path: '/matrices'
      fullPath: '/studies/$studyId/explore/modelization/areas/$areaId/thermals/$thermalId/matrices'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdMatricesRouteImport
      parentRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAboutRoute: typeof AuthenticatedSettingsAboutRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsMaintenanceRoute: typeof AuthenticatedSettingsMaintenanceRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsGroupsIndexRoute: typeof AuthenticatedSettingsGroupsIndexRoute
  AuthenticatedSettingsTokensIndexRoute: typeof AuthenticatedSettingsTokensIndexRoute
  AuthenticatedSettingsUsersIndexRoute: typeof AuthenticatedSettingsUsersIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAboutRoute: AuthenticatedSettingsAboutRoute,
    AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
    AuthenticatedSettingsMaintenanceRoute:
      AuthenticatedSettingsMaintenanceRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
    AuthenticatedSettingsGroupsIndexRoute:
      AuthenticatedSettingsGroupsIndexRoute,
    AuthenticatedSettingsTokensIndexRoute:
      AuthenticatedSettingsTokensIndexRoute,
    AuthenticatedSettingsUsersIndexRoute: AuthenticatedSettingsUsersIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchRouteRouteChildren {
  AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchPerimeterRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchPerimeterRoute
  AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchIndexRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchIndexRoute
  AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchGeneralIndexRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchGeneralIndexRoute
}

const AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchRouteRouteChildren: AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchRouteRouteChildren =
  {
    AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchPerimeterRoute:
      AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchPerimeterRoute,
    AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchIndexRoute:
      AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchIndexRoute,
    AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchGeneralIndexRoute:
      AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchGeneralIndexRoute,
  }

const AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchRouteRouteWithChildren =
  AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchRouteRoute._addFileChildren(
    AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchRouteRouteChildren,
  )

interface AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRouteChildren {
  AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingAreasRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingAreasRoute
  AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingBindingConstraintsRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingBindingConstraintsRoute
  AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingLinksRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingLinksRoute
  AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingIndexRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingIndexRoute
}

const AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRouteChildren: AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRouteChildren =
  {
    AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingAreasRoute:
      AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingAreasRoute,
    AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingBindingConstraintsRoute:
      AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingBindingConstraintsRoute,
    AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingLinksRoute:
      AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingLinksRoute,
    AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingIndexRoute:
      AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingIndexRoute,
  }

const AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRouteWithChildren =
  AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRoute._addFileChildren(
    AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRouteChildren,
  )

interface AuthenticatedStudiesStudyIdExploreConfigurationRouteRouteChildren {
  AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchRouteRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchRouteRouteWithChildren
  AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRouteWithChildren
  AuthenticatedStudiesStudyIdExploreConfigurationEcoOptionsRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationEcoOptionsRoute
  AuthenticatedStudiesStudyIdExploreConfigurationIndexRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationIndexRoute
  AuthenticatedStudiesStudyIdExploreConfigurationAdvancedParamsIndexRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationAdvancedParamsIndexRoute
  AuthenticatedStudiesStudyIdExploreConfigurationGeneralIndexRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationGeneralIndexRoute
  AuthenticatedStudiesStudyIdExploreConfigurationOptimizationIndexRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationOptimizationIndexRoute
  AuthenticatedStudiesStudyIdExploreConfigurationTsGenerationIndexRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationTsGenerationIndexRoute
}

const AuthenticatedStudiesStudyIdExploreConfigurationRouteRouteChildren: AuthenticatedStudiesStudyIdExploreConfigurationRouteRouteChildren =
  {
    AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchRouteRoute:
      AuthenticatedStudiesStudyIdExploreConfigurationAdequacyPatchRouteRouteWithChildren,
    AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRoute:
      AuthenticatedStudiesStudyIdExploreConfigurationGeoTrimmingRouteRouteWithChildren,
    AuthenticatedStudiesStudyIdExploreConfigurationEcoOptionsRoute:
      AuthenticatedStudiesStudyIdExploreConfigurationEcoOptionsRoute,
    AuthenticatedStudiesStudyIdExploreConfigurationIndexRoute:
      AuthenticatedStudiesStudyIdExploreConfigurationIndexRoute,
    AuthenticatedStudiesStudyIdExploreConfigurationAdvancedParamsIndexRoute:
      AuthenticatedStudiesStudyIdExploreConfigurationAdvancedParamsIndexRoute,
    AuthenticatedStudiesStudyIdExploreConfigurationGeneralIndexRoute:
      AuthenticatedStudiesStudyIdExploreConfigurationGeneralIndexRoute,
    AuthenticatedStudiesStudyIdExploreConfigurationOptimizationIndexRoute:
      AuthenticatedStudiesStudyIdExploreConfigurationOptimizationIndexRoute,
    AuthenticatedStudiesStudyIdExploreConfigurationTsGenerationIndexRoute:
      AuthenticatedStudiesStudyIdExploreConfigurationTsGenerationIndexRoute,
  }

const AuthenticatedStudiesStudyIdExploreConfigurationRouteRouteWithChildren =
  AuthenticatedStudiesStudyIdExploreConfigurationRouteRoute._addFileChildren(
    AuthenticatedStudiesStudyIdExploreConfigurationRouteRouteChildren,
  )

interface AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdRouteRouteChildren {
  AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdMatricesRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdMatricesRoute
  AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdParametersRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdParametersRoute
  AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdIndexRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdIndexRoute
}

const AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdRouteRouteChildren: AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdRouteRouteChildren =
  {
    AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdMatricesRoute:
      AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdMatricesRoute,
    AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdParametersRoute:
      AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdParametersRoute,
    AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdIndexRoute:
      AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdIndexRoute,
  }

const AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdRouteRouteWithChildren =
  AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdRouteRoute._addFileChildren(
    AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdRouteRouteChildren,
  )

interface AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRouteChildren {
  AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdLoadRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdLoadRoute
  AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdIndexRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdIndexRoute
  AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdRouteRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdRouteRouteWithChildren
  AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdPropertiesIndexRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdPropertiesIndexRoute
  AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsIndexRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsIndexRoute
}

const AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRouteChildren: AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRouteChildren =
  {
    AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdLoadRoute:
      AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdLoadRoute,
    AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdIndexRoute:
      AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdIndexRoute,
    AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdRouteRoute:
      AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsThermalIdRouteRouteWithChildren,
    AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdPropertiesIndexRoute:
      AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdPropertiesIndexRoute,
    AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsIndexRoute:
      AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdThermalsIndexRoute,
  }

const AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRouteWithChildren =
  AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRoute._addFileChildren(
    AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRouteChildren,
  )

interface AuthenticatedStudiesStudyIdExploreModelizationAreasRouteRouteChildren {
  AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRouteWithChildren
}

const AuthenticatedStudiesStudyIdExploreModelizationAreasRouteRouteChildren: AuthenticatedStudiesStudyIdExploreModelizationAreasRouteRouteChildren =
  {
    AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRoute:
      AuthenticatedStudiesStudyIdExploreModelizationAreasAreaIdRouteRouteWithChildren,
  }

const AuthenticatedStudiesStudyIdExploreModelizationAreasRouteRouteWithChildren =
  AuthenticatedStudiesStudyIdExploreModelizationAreasRouteRoute._addFileChildren(
    AuthenticatedStudiesStudyIdExploreModelizationAreasRouteRouteChildren,
  )

interface AuthenticatedStudiesStudyIdExploreModelizationRouteRouteChildren {
  AuthenticatedStudiesStudyIdExploreModelizationAreasRouteRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationAreasRouteRouteWithChildren
  AuthenticatedStudiesStudyIdExploreModelizationIndexRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationIndexRoute
  AuthenticatedStudiesStudyIdExploreModelizationMapIndexRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationMapIndexRoute
}

const AuthenticatedStudiesStudyIdExploreModelizationRouteRouteChildren: AuthenticatedStudiesStudyIdExploreModelizationRouteRouteChildren =
  {
    AuthenticatedStudiesStudyIdExploreModelizationAreasRouteRoute:
      AuthenticatedStudiesStudyIdExploreModelizationAreasRouteRouteWithChildren,
    AuthenticatedStudiesStudyIdExploreModelizationIndexRoute:
      AuthenticatedStudiesStudyIdExploreModelizationIndexRoute,
    AuthenticatedStudiesStudyIdExploreModelizationMapIndexRoute:
      AuthenticatedStudiesStudyIdExploreModelizationMapIndexRoute,
  }

const AuthenticatedStudiesStudyIdExploreModelizationRouteRouteWithChildren =
  AuthenticatedStudiesStudyIdExploreModelizationRouteRoute._addFileChildren(
    AuthenticatedStudiesStudyIdExploreModelizationRouteRouteChildren,
  )

interface AuthenticatedStudiesStudyIdExploreTablemodeRouteRouteChildren {
  AuthenticatedStudiesStudyIdExploreTablemodeTableModeIdIndexRoute: typeof AuthenticatedStudiesStudyIdExploreTablemodeTableModeIdIndexRoute
}

const AuthenticatedStudiesStudyIdExploreTablemodeRouteRouteChildren: AuthenticatedStudiesStudyIdExploreTablemodeRouteRouteChildren =
  {
    AuthenticatedStudiesStudyIdExploreTablemodeTableModeIdIndexRoute:
      AuthenticatedStudiesStudyIdExploreTablemodeTableModeIdIndexRoute,
  }

const AuthenticatedStudiesStudyIdExploreTablemodeRouteRouteWithChildren =
  AuthenticatedStudiesStudyIdExploreTablemodeRouteRoute._addFileChildren(
    AuthenticatedStudiesStudyIdExploreTablemodeRouteRouteChildren,
  )

interface AuthenticatedStudiesStudyIdExploreXpansionRouteRouteChildren {
  AuthenticatedStudiesStudyIdExploreXpansionCapacitiesRoute: typeof AuthenticatedStudiesStudyIdExploreXpansionCapacitiesRoute
  AuthenticatedStudiesStudyIdExploreXpansionConstraintsRoute: typeof AuthenticatedStudiesStudyIdExploreXpansionConstraintsRoute
  AuthenticatedStudiesStudyIdExploreXpansionWeightsRoute: typeof AuthenticatedStudiesStudyIdExploreXpansionWeightsRoute
  AuthenticatedStudiesStudyIdExploreXpansionIndexRoute: typeof AuthenticatedStudiesStudyIdExploreXpansionIndexRoute
  AuthenticatedStudiesStudyIdExploreXpansionCandidatesIndexRoute: typeof AuthenticatedStudiesStudyIdExploreXpansionCandidatesIndexRoute
  AuthenticatedStudiesStudyIdExploreXpansionSettingsIndexRoute: typeof AuthenticatedStudiesStudyIdExploreXpansionSettingsIndexRoute
}

const AuthenticatedStudiesStudyIdExploreXpansionRouteRouteChildren: AuthenticatedStudiesStudyIdExploreXpansionRouteRouteChildren =
  {
    AuthenticatedStudiesStudyIdExploreXpansionCapacitiesRoute:
      AuthenticatedStudiesStudyIdExploreXpansionCapacitiesRoute,
    AuthenticatedStudiesStudyIdExploreXpansionConstraintsRoute:
      AuthenticatedStudiesStudyIdExploreXpansionConstraintsRoute,
    AuthenticatedStudiesStudyIdExploreXpansionWeightsRoute:
      AuthenticatedStudiesStudyIdExploreXpansionWeightsRoute,
    AuthenticatedStudiesStudyIdExploreXpansionIndexRoute:
      AuthenticatedStudiesStudyIdExploreXpansionIndexRoute,
    AuthenticatedStudiesStudyIdExploreXpansionCandidatesIndexRoute:
      AuthenticatedStudiesStudyIdExploreXpansionCandidatesIndexRoute,
    AuthenticatedStudiesStudyIdExploreXpansionSettingsIndexRoute:
      AuthenticatedStudiesStudyIdExploreXpansionSettingsIndexRoute,
  }

const AuthenticatedStudiesStudyIdExploreXpansionRouteRouteWithChildren =
  AuthenticatedStudiesStudyIdExploreXpansionRouteRoute._addFileChildren(
    AuthenticatedStudiesStudyIdExploreXpansionRouteRouteChildren,
  )

interface AuthenticatedStudiesStudyIdExploreRouteRouteChildren {
  AuthenticatedStudiesStudyIdExploreConfigurationRouteRoute: typeof AuthenticatedStudiesStudyIdExploreConfigurationRouteRouteWithChildren
  AuthenticatedStudiesStudyIdExploreModelizationRouteRoute: typeof AuthenticatedStudiesStudyIdExploreModelizationRouteRouteWithChildren
  AuthenticatedStudiesStudyIdExploreTablemodeRouteRoute: typeof AuthenticatedStudiesStudyIdExploreTablemodeRouteRouteWithChildren
  AuthenticatedStudiesStudyIdExploreXpansionRouteRoute: typeof AuthenticatedStudiesStudyIdExploreXpansionRouteRouteWithChildren
  AuthenticatedStudiesStudyIdExploreIndexRoute: typeof AuthenticatedStudiesStudyIdExploreIndexRoute
  AuthenticatedStudiesStudyIdExploreDebugIndexRoute: typeof AuthenticatedStudiesStudyIdExploreDebugIndexRoute
  AuthenticatedStudiesStudyIdExploreOutputsIndexRoute: typeof AuthenticatedStudiesStudyIdExploreOutputsIndexRoute
  AuthenticatedStudiesStudyIdExploreOutputsOutputIdIndexRoute: typeof AuthenticatedStudiesStudyIdExploreOutputsOutputIdIndexRoute
}

const AuthenticatedStudiesStudyIdExploreRouteRouteChildren: AuthenticatedStudiesStudyIdExploreRouteRouteChildren =
  {
    AuthenticatedStudiesStudyIdExploreConfigurationRouteRoute:
      AuthenticatedStudiesStudyIdExploreConfigurationRouteRouteWithChildren,
    AuthenticatedStudiesStudyIdExploreModelizationRouteRoute:
      AuthenticatedStudiesStudyIdExploreModelizationRouteRouteWithChildren,
    AuthenticatedStudiesStudyIdExploreTablemodeRouteRoute:
      AuthenticatedStudiesStudyIdExploreTablemodeRouteRouteWithChildren,
    AuthenticatedStudiesStudyIdExploreXpansionRouteRoute:
      AuthenticatedStudiesStudyIdExploreXpansionRouteRouteWithChildren,
    AuthenticatedStudiesStudyIdExploreIndexRoute:
      AuthenticatedStudiesStudyIdExploreIndexRoute,
    AuthenticatedStudiesStudyIdExploreDebugIndexRoute:
      AuthenticatedStudiesStudyIdExploreDebugIndexRoute,
    AuthenticatedStudiesStudyIdExploreOutputsIndexRoute:
      AuthenticatedStudiesStudyIdExploreOutputsIndexRoute,
    AuthenticatedStudiesStudyIdExploreOutputsOutputIdIndexRoute:
      AuthenticatedStudiesStudyIdExploreOutputsOutputIdIndexRoute,
  }

const AuthenticatedStudiesStudyIdExploreRouteRouteWithChildren =
  AuthenticatedStudiesStudyIdExploreRouteRoute._addFileChildren(
    AuthenticatedStudiesStudyIdExploreRouteRouteChildren,
  )

interface AuthenticatedStudiesStudyIdRouteRouteChildren {
  AuthenticatedStudiesStudyIdExploreRouteRoute: typeof AuthenticatedStudiesStudyIdExploreRouteRouteWithChildren
  AuthenticatedStudiesStudyIdIndexRoute: typeof AuthenticatedStudiesStudyIdIndexRoute
}

const AuthenticatedStudiesStudyIdRouteRouteChildren: AuthenticatedStudiesStudyIdRouteRouteChildren =
  {
    AuthenticatedStudiesStudyIdExploreRouteRoute:
      AuthenticatedStudiesStudyIdExploreRouteRouteWithChildren,
    AuthenticatedStudiesStudyIdIndexRoute:
      AuthenticatedStudiesStudyIdIndexRoute,
  }

const AuthenticatedStudiesStudyIdRouteRouteWithChildren =
  AuthenticatedStudiesStudyIdRouteRoute._addFileChildren(
    AuthenticatedStudiesStudyIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedStudiesStudyIdRouteRoute: typeof AuthenticatedStudiesStudyIdRouteRouteWithChildren
  AuthenticatedApidocIndexRoute: typeof AuthenticatedApidocIndexRoute
  AuthenticatedDataIndexRoute: typeof AuthenticatedDataIndexRoute
  AuthenticatedStudiesIndexRoute: typeof AuthenticatedStudiesIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedStudiesStudyIdRouteRoute:
    AuthenticatedStudiesStudyIdRouteRouteWithChildren,
  AuthenticatedApidocIndexRoute: AuthenticatedApidocIndexRoute,
  AuthenticatedDataIndexRoute: AuthenticatedDataIndexRoute,
  AuthenticatedStudiesIndexRoute: AuthenticatedStudiesIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
