docs_dir: docs
site_name: Antares Web Documentation
repo_url: https://github.com/AntaresSimulatorTeam/AntaREST
edit_uri: edit/doc/docs/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/Icone.png
  prev_next_buttons_location: none
  features:
    - navigation.instant
    - navigation.top
    - navigation.expand
  #  - navigation.sections
  #   - header.autohide
  #   - toc.separate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: antares
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: 'index.md'
  - 'User guide':
      - 'Introduction': 'user-guide/0-introduction.md'
      - 'User interface': 'user-guide/1-interface.md'
      - 'Study Modelization':
          - 'Overview': 'user-guide/2-study.md'
          - 'Map': 'user-guide/study/01-map.md'
          - 'Area Configuration':
              - 'Overview': 'user-guide/study/02-areas.md'
              - 'General Properties': 'user-guide/study/areas/01-properties.md'
              - 'Load': 'user-guide/study/areas/02-load.md'
              - 'Thermal Clusters': 'user-guide/study/areas/03-thermals.md'
              - 'Renewables Clusters': 'user-guide/study/areas/04-renewables.md'
              - 'Hydraulic Generators': 'user-guide/study/areas/05-hydro.md'
              - 'Wind Generators': 'user-guide/study/areas/06-wind.md'
              - 'Solar Generators': 'user-guide/study/areas/07-solar.md'
              - 'Short-Term Storages': 'user-guide/study/areas/08-st-storages.md'
              - 'Reserves': 'user-guide/study/areas/09-reserves.md'
              - 'Miscellaneous Generators': 'user-guide/study/areas/10-misc-gen.md'
          - 'Links': 'user-guide/study/03-links.md'
          - 'Binding Constraints': 'user-guide/study/04-binding-constraints.md'
      - 'Simulation Configuration':
          'General Configuration': 'user-guide/simulation-configuration/all-configurations.md#general-configuration'
          'TS management': 'user-guide/simulation-configuration/all-configurations.md#Time-series management'
          'Optimization preferences': 'user-guide/simulation-configuration/all-configurations.md#optimization-preferences'
          'Adequacy Patch': 'user-guide/simulation-configuration/all-configurations.md#adequacy-patch'
          'Advanced parameters': 'user-guide/simulation-configuration/all-configurations.md#advanced-parameters'
          'Economic Opt.': 'user-guide/simulation-configuration/all-configurations.md#economic-opt'
          'Geographic Trimming (Areas)': 'user-guide/simulation-configuration/all-configurations.md#geographic-trimming(areas)'
          'Geographic Trimming (Links)': 'user-guide/simulation-configuration/all-configurations.md#geographic-trimming(links)'
          'Geographic Trimming (Binding Constraints)': 'user-guide/simulation-configuration/all-configurations.md#geographic-trimming(binding-constrainte)'
      - 'Table Mode': 'user-guide/study/06-table-mode.md'
      - 'Xpansion' : user-guide/study/07-xpansion.md
      - 'Results' : user-guide/study/08-results.md
      - 'Debug': 'user-guide/study/05-debug.md'
      - 'Variant manager': 'user-guide/3-variant_manager.md'
      - 'How to':
          - 'Create a study': 'user-guide/how-to/studies-create.md'
          - 'Import a study': 'user-guide/how-to/studies-import.md'
          - 'Upgrade a study': 'user-guide/how-to/studies-upgrade.md'
  - 'Developer guide':
      - 'Build':
          - 'Introduction': 'developer-guide/install/0-INSTALL.md'
          - 'Configuration': 'developer-guide/install/1-CONFIG.md'
          - 'Deployment': 'developer-guide/install/2-DEPLOY.md'
      - 'Architecture': 'developer-guide/architecture/0-introduction.md'
      - 'Database management': 'developer-guide/architecture/1-database.md'
      - 'Add a new study version': 'developer-guide/1-add-new-antares-version.md'
      - 'Changelog': 'CHANGELOG.md'
      - 'Roadmap': 'developer-guide/2-roadmap.md'
  - 'External links' :
    - 'Antares ecosystem': 'https://antares-doc.readthedocs.io'
    - 'Antares website' : 'https://antares-simulator.org/'
    - 'RTE website' : 'http://www.rte-france.com/'

extra:
  generator: false
  version:
    provider: mike
plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://code.jquery.com/jquery-3.6.0.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed

copyright: Copyright &copy; 2007 - 2024 RTE