docs_dir: docs
site_name: Antares Web Documentation
repo_url: https://github.com/AntaresSimulatorTeam/AntaREST
edit_uri: edit/doc/docs/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/Icone.png
  prev_next_buttons_location: none
  features:
    - navigation.instant
    - navigation.top
    - navigation.expand
  #  - navigation.sections
  #   - header.autohide
  #   - toc.separate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: antares
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: 'index.md'
  - 'User guide':
      - 'Introduction': 'user-guide/0-introduction.md'
      - 'User interface': 'user-guide/1-interface.md'
      - 'Study Configuration':
          - 'Main Topics': 'user-guide/2-study.md'
          - 'Map':
              - 'Main Topics': 'user-guide/study/01-map.md'
          - 'Area Configuration':
              - 'Main Topics': 'user-guide/study/02-areas.md'
              - 'General Properties': 'user-guide/study/areas/01-properties.md'
              - 'Load': 'user-guide/study/areas/02-load.md'
              - 'Thermal Clusters': 'user-guide/study/areas/03-thermals.md'
              - 'Renewables Clusters': 'user-guide/study/areas/04-renewables.md'
              - 'Hydraulic Generators': 'user-guide/study/areas/05-hydro.md'
              - 'Wind Generators': 'user-guide/study/areas/06-wind.md'
              - 'Solar Generators': 'user-guide/study/areas/07-solar.md'
              - 'Short-Term Storages': 'user-guide/study/areas/08-st-storages.md'
              - 'Reserves': 'user-guide/study/areas/09-reserves.md'
              - 'Miscellaneous Generators': 'user-guide/study/areas/10-misc-gen.md'
          - 'Links':
              - 'Main Topics': 'user-guide/study/03-links.md'
          - 'Binding Constraints':
              - 'Main Topics': 'user-guide/study/04-binding-constraints.md'
          - 'Debug':
              - 'Main Topics': 'user-guide/study/05-debug.md'
          - 'Table Mode':
              - 'Main Topics': 'user-guide/study/06-table-mode.md'
      - 'Variant manager': 'user-guide/3-variant_manager.md'
  - 'How to':
      - 'Import a study': 'how-to/studies-import.md'
      - 'Upgrade a study': 'how-to/studies-upgrade.md'
  - 'Build':
      - 'Introduction': 'install/0-INSTALL.md'
      - 'Configuration': 'install/1-CONFIG.md'
      - 'Deployment': 'install/2-DEPLOY.md'
  - 'Develop':
      - 'Introduction': 'architecture/0-introduction.md'
      - 'Database management': 'architecture/1-database.md'
      - 'Add a new Study version': 'architecture/2-add-new-antares-version.md'
      - 'Roadmap': 'architecture/5-roadmap.md'
  - 'Antares ecosystem': 'https://antares-doc.readthedocs.io'
  - 'Changelog': 'CHANGELOG.md'

extra:
  generator: false
  version:
    provider: mike
plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://code.jquery.com/jquery-3.6.0.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed

copyright: Copyright &copy; 2007 - 2023 RTE