docs_dir: docs
site_name: Antares Web Documentation
repo_name: AntaREST
repo_url: https://github.com/AntaresSimulatorTeam/AntaREST
edit_uri: edit/dev/docs

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/icone.png
  prev_next_buttons_location: none
  features:
    - navigation.instant
    - navigation.top
    - content.action.edit
    - content.action.view
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: antares
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - Build from source: installation.md
  - Configuration: configuration.md
  - Deployment: deploy.md
  - Architecture: architecture.md
  - Database management: database.md
  - Add a new study version: add-new-antares-version.md
  - Changelog: CHANGELOG.md
  - Contributing: contributing.md
  
extra:
  generator: false
  version:
    provider: mike
plugins:
  - search

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed

copyright: Copyright &copy; 2007 - 2026 RTE