"""update_study

Revision ID: 0146b79f723c
Revises: 3292cdb4557a
Create Date: 2021-09-06 18:42:12.670422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0146b79f723c'
down_revision = '3292cdb4557a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rawstudy', schema=None) as batch_op:
        batch_op.drop_column('path')

    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(length=255), nullable=True))

    with op.batch_alter_table('variantstudy', schema=None) as batch_op:
        batch_op.drop_column('path')
        batch_op.drop_column('workspace')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variantstudy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('path', sa.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.drop_column('path')

    with op.batch_alter_table('rawstudy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
