"""Add solver_presets table

Revision ID: 04a098a4a38e
Revises: a9dfa0e1f23d
Create Date: 2025-10-23 11:17:03.210771

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "04a098a4a38e"
down_revision = "a9dfa0e1f23d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "solver_presets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("linear_solver", sa.String(), nullable=False),
        sa.Column("min_antares_version", sa.String(), nullable=True),
        sa.Column("max_antares_version", sa.String(), nullable=True),
        sa.Column("linear_solver_param_optim_1", sa.TEXT(), nullable=True),
        sa.Column("linear_solver_param_optim_2", sa.TEXT(), nullable=True),
        sa.Column("linear_solver_param", sa.TEXT(), nullable=True),
        sa.Column("use_optim_1_basis_next_week", sa.Boolean(), nullable=False),
        sa.Column("use_optim_1_basis_optim_2", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("solver_presets")
