"""add_task_type

Revision ID: 23ff8deddb4a
Revises: 298aecf6ea40
Create Date: 2022-01-25 09:50:17.304650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ff8deddb4a'
down_revision = '298aecf6ea40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskjob', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ref_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskjob', schema=None) as batch_op:
        batch_op.drop_column('ref_id')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
