"""add_job_solver_stats

Revision ID: 26c50ef2a0e1
Revises: c9dcca887456
Create Date: 2022-06-08 18:19:30.858085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c50ef2a0e1'
down_revision = 'c9dcca887456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solver_stats', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_result', schema=None) as batch_op:
        batch_op.drop_column('solver_stats')

    # ### end Alembic commands ###
