"""add_configdata

Revision ID: 298aecf6ea40
Revises: a845d5eae88e
Create Date: 2022-01-07 17:07:21.389595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298aecf6ea40'
down_revision = 'a845d5eae88e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configdata',
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('owner', 'key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configdata')
    # ### end Alembic commands ###
