"""fix_permissions

Revision ID: 2a8c5e41f214
Revises: 76dd045d12f4
Create Date: 2022-03-04 15:26:27.793630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8c5e41f214'
down_revision = '76dd045d12f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_context().dialect.name == 'sqlite':
        return
    op.execute("GRANT USAGE, SELECT ON SEQUENCE launcherjoblog_id_sequence TO public;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
