"""add_tasks

Revision ID: 2ed6bf9f1690
Revises: ae61e887e309
Create Date: 2021-08-19 14:56:38.632677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import Sequence
from sqlalchemy.sql.ddl import CreateSequence, DropSequence

revision = '2ed6bf9f1690'
down_revision = 'ae61e887e309'
branch_labels = None
depends_on = None


def upgrade():
    if op.get_context().dialect.supports_sequences:
        op.execute(CreateSequence(Sequence('tasklog_id_sequence')))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskjob',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('result_msg', sa.String(), nullable=True),
    sa.Column('result_status', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taskjoblog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['taskjob.id'], name='fk_log_taskjob_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taskjoblog')
    op.drop_table('taskjob')
    # ### end Alembic commands ###

    if op.get_context().dialect.supports_sequences:
        op.execute(DropSequence(Sequence('tasklog_id_sequence')))

