"""empty message

Revision ID: 3292cdb4557a
Revises: ae61e887e309
Create Date: 2021-08-19 18:05:58.413966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3292cdb4557a"
down_revision = "2ed6bf9f1690"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "variantstudy",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("path", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["study.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "commandblock",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("study_id", sa.String(length=36), nullable=True),
        sa.Column("index", sa.Integer(), nullable=True),
        sa.Column("command", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("args", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["variantstudy.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "variant_study_snapshot",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("path", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["variantstudy.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("parent_id", sa.String(length=36), nullable=True)
        )
        batch_op.create_foreign_key(
            "fk_study_study_id", "study", ["parent_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.drop_constraint("fk_study_study_id", type_="foreignkey")
        batch_op.drop_column("parent_id")

    op.drop_table("variant_study_snapshot")
    op.drop_table("commandblock")
    op.drop_table("variantstudy")
    # ### end Alembic commands ###
