"""add_filetransfer_manager

Revision ID: 415976c0a4d4
Revises: 9846e90c2868
Create Date: 2021-11-22 13:28:31.698683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415976c0a4d4'
down_revision = '9846e90c2868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_download',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('ready', sa.Boolean(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_download')
    # ### end Alembic commands ###
