"""sequence_creation

Revision ID: 512a751033dd
Revises: 47ab888dc44d
Create Date: 2021-07-26 10:41:33.033615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence

# revision identifiers, used by Alembic.
from sqlalchemy.sql.ddl import DropSequence

revision = '512a751033dd'
down_revision = '47ab888dc44d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_context().dialect.supports_sequences:
        op.execute(CreateSequence(Sequence('identity_id_seq')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_context().dialect.supports_sequences:
        op.execute(DropSequence(Sequence('identity_id_seq')))
    # ### end Alembic commands ###
