"""add_task_type

Revision ID: 5cb8c14b3fcf
Revises: 298aecf6ea40
Create Date: 2022-01-24 16:02:51.917984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb8c14b3fcf'
down_revision = '298aecf6ea40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskjob', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskjob', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
