"""rawstudies_folder_info

Revision ID: 63ed81e5ce6f
Revises: ab143a39c4db
Create Date: 2021-09-27 18:23:44.909595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import text
from sqlalchemy.engine import Connection

revision = '63ed81e5ce6f'
down_revision = 'f3b1b3fb31f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rawstudy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rawstudy', schema=None) as batch_op:
        batch_op.drop_column('folder')

    # ### end Alembic commands ###
