"""Add tag and study_tag tables

Revision ID: 6a6634ed2c2f
Revises: 1f5db5dfad80
Create Date: 2024-01-30 18:07:11.116834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6634ed2c2f'
down_revision = '1f5db5dfad80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('label')
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_color'), ['color'], unique=False)
        batch_op.create_index(batch_op.f('ix_tag_label'), ['label'], unique=False)

    op.create_table('study_tag',
    sa.Column('study_id', sa.String(length=36), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag'], ['tag.label'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_id', 'tag')
    )
    with op.batch_alter_table('study_tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_tag_study_id'), ['study_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_tag_tag'), ['tag'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_tag_tag'))
        batch_op.drop_index(batch_op.f('ix_study_tag_study_id'))

    op.drop_table('study_tag')
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_label'))
        batch_op.drop_index(batch_op.f('ix_tag_color'))

    op.drop_table('tag')
    # ### end Alembic commands ###
