"""add_launcher_job_logs

Revision ID: 76dd045d12f4
Revises: f5aed532a99c
Create Date: 2022-02-25 16:56:29.622137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import Sequence
from sqlalchemy.sql.ddl import CreateSequence, DropSequence

revision = '76dd045d12f4'
down_revision = 'f5aed532a99c'
branch_labels = None
depends_on = None


def upgrade():
    if op.get_context().dialect.supports_sequences:
        op.execute(CreateSequence(Sequence("launcherjoblog_id_sequence")))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('launcherjoblog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('log_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_result.id'], name='fk_log_job_result_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('launcherjoblog')
    # ### end Alembic commands ###

    if op.get_context().dialect.supports_sequences:
        op.execute(DropSequence(Sequence("launcherjoblog_id_sequence")))