"""variant_generation_task

Revision ID: ab143a39c4db
Revises: 55138d877c6a
Create Date: 2021-09-25 16:27:42.489498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab143a39c4db'
down_revision = '55138d877c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskjob', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.String(), nullable=True))

    with op.batch_alter_table('variantstudy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generation_task', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variantstudy', schema=None) as batch_op:
        batch_op.drop_column('generation_task')

    with op.batch_alter_table('taskjob', schema=None) as batch_op:
        batch_op.drop_column('result')

    # ### end Alembic commands ###
