"""fix_permissions

Revision ID: c83b8bb38a7c
Revises: 0146b79f723c
Create Date: 2021-09-10 11:48:32.778790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83b8bb38a7c'
down_revision = '0146b79f723c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_context().dialect.name == 'sqlite':
        return
    op.execute("GRANT USAGE, SELECT ON SEQUENCE tasklog_id_sequence TO public;")
    #op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO public;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
