"""create launcher_config table

Revision ID: d87f410934f1
Revises: d2942741ae68
Create Date: 2025-10-08 16:41:39.488774

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d87f410934f1"
down_revision = "d2942741ae68"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "launcher_configuration",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("linear_solver", sa.String(), nullable=False),
        sa.Column("min_antares_version", sa.String(), nullable=True),
        sa.Column("max_antares_version", sa.String(), nullable=True),
        sa.Column("linear_solver_param_optim_1", sa.JSON(), nullable=True),
        sa.Column("linear_solver_param_optim_2", sa.JSON(), nullable=True),
        sa.Column("linear_solver_param", sa.JSON(), nullable=True),
        sa.Column("use_optim_1_basis_next_week", sa.Boolean(), nullable=False),
        sa.Column("use_optim_1_basis_optim_2", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("launcher_configuration")
