"""update_datetime

Revision ID: dcbe7dbf500b
Revises: 63ed81e5ce6f
Create Date: 2021-11-17 16:10:35.914371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import Connection

# revision identifiers, used by Alembic.
revision = 'dcbe7dbf500b'
down_revision = '63ed81e5ce6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connexion: Connection = op.get_bind()
    rawstudies = connexion.execute(
        "SELECT d.created_at, d.updated_at, jr.completion_date, jr.creation_date, s.created_at, s.updated_at  FROM dataset")
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
