"""add_last_access_study_prop

Revision ID: e65e0c04606b
Revises: 26c50ef2a0e1
Create Date: 2022-08-09 12:48:55.860099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65e0c04606b'
down_revision = '26c50ef2a0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_access', sa.DateTime(), nullable=True))



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.drop_column('last_access')

    # ### end Alembic commands ###
