"""add_study_additional_data

Revision ID: e6bb88859884
Revises: ef72a8a1c9cf
Create Date: 2022-04-20 14:30:54.685433

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e6bb88859884'
down_revision = 'f83043f34a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_additional_data',
    sa.Column('study_id', sa.String(length=36), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('horizon', sa.String(), nullable=True),
    sa.Column('patch', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.PrimaryKeyConstraint('study_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_additional_data')
    # ### end Alembic commands ###
