"""rawstudies_folder_info

Revision ID: 63ed81e5ce6f
Revises: ab143a39c4db
Create Date: 2021-09-27 18:23:44.909595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import text
from sqlalchemy.engine import Connection

revision = 'rp986cf862cy'
down_revision = 'b2f7e9a1c4d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tablemode',
        sa.Column('table_id', sa.Uuid(), nullable=False),
                sa.Column('table_name', sa.String(length=255), nullable=False),
                sa.Column('user_id', sa.Integer(), nullable=False, index=True),
                sa.Column('table_type', sa.String(length=255), nullable=False),
                sa.Column('table_columns', sa.String(), nullable=False),
                sa.PrimaryKeyConstraint('table_id', 'user_id', name="pk_table_id"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tablemode')

    # ### end Alembic commands ###
