"""add_tablemode_table

Revision ID: 63ed81e5ce6f
Revises: ab143a39c4db
Create Date: 2026-05-06 09:22:43.268409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import text
from sqlalchemy.engine import Connection

revision = 'rp986cf862cy'
down_revision = 'b2f7e9a1c4d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tablemode',
        sa.Column('table_id', sa.Uuid(), nullable=False),
                sa.Column('table_name', sa.String(length=255), nullable=False),
                sa.Column('user_id', sa.Integer(), nullable=False),
                sa.Column('table_type', sa.String(length=255), nullable=False),
                sa.Column('table_columns', sa.String(), nullable=False),
                sa.PrimaryKeyConstraint('table_id', name="pk_table_id"),
                sa.ForeignKeyConstraint(['user_id'], ['identities.id'], name="fk_user_id_tablemode", ondelete="CASCADE"),
    )
    op.create_index(op.f('ix_user_id'), 'tablemode', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='tablemode')
    op.drop_table('tablemode')

    # ### end Alembic commands ###
