"""fix study owner

Revision ID: 576c82a5626e
Revises: a12f9bf62597
Create Date: 2021-05-31 12:46:23.641879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576c82a5626e'
down_revision = 'a12f9bf62597'
branch_labels = None
depends_on = None

convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study', schema=None, naming_convention=convention) as batch_op:
        batch_op.drop_constraint('fk_study_owner_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_study_owner_id_identities'), 'identities', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study', schema=None, naming_convention=convention) as batch_op:
        batch_op.drop_constraint('fk_study_owner_id_identities', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_study_owner_id_users'), 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###
