"""Update login

Revision ID: a12f9bf62597
Revises: 5bf739353855
Create Date: 2021-05-19 14:20:24.072508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12f9bf62597'
down_revision = '5bf739353855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('type', sa.Enum('ADMIN', 'RUNNER', 'WRITER', 'READER', name='roletype'), nullable=True),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('identity_id', 'group_id')
    )
    op.create_table('users_ldap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('is_author', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['identities.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('public_mode', sa.Enum('NONE', 'READ', 'EXECUTE', 'EDIT', 'FULL', name='publicmode'), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('rawstudy',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content_status', sa.Enum('VALID', 'WARNING', 'ERROR', name='studycontentstatus'), nullable=True),
    sa.Column('workspace', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['study.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('metadata')
    op.drop_table('users_groups')
    op.drop_table('group_metadata')
    op.create_table('group_metadata',
    sa.Column('study_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    )
    op.drop_table('users')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_pwd', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['id'], ['identities.id'], ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.add_column('group_metadata', sa.Column('metadata_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'group_metadata', type_='foreignkey')
    op.create_foreign_key(None, 'group_metadata', 'metadata', ['metadata_id'], ['id'])
    op.drop_column('group_metadata', 'study_id')
    op.create_table('users_groups',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('metadata',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('version', sa.VARCHAR(length=255), nullable=True),
    sa.Column('author', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('content_status', sa.VARCHAR(length=7), nullable=True),
    sa.Column('public', sa.BOOLEAN(), nullable=True),
    sa.Column('workspace', sa.VARCHAR(length=255), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint("content_status IN ('VALID', 'WARNING', 'ERROR')", name='studycontentstatus'),
    sa.CheckConstraint('public IN (0, 1)'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('rawstudy')
    op.drop_table('study')
    op.drop_table('bots')
    op.drop_table('users_ldap')
    op.drop_table('roles')
    op.drop_table('identities')
    # ### end Alembic commands ###
