# Copyright (c) 2025, RTE (https://www.rte-france.com)
#
# See AUTHORS.txt
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0
#
# This file is part of the Antares project.

from unittest.mock import ANY

from starlette.testclient import TestClient

from antarest.core.tasks.model import TaskStatus
from tests.integration.utils import wait_task_completion


def test_antares_craft(client: TestClient, user_access_token: str, internal_study_id: str) -> None:
    client.headers = {"Authorization": f"Bearer {user_access_token}"}

    # If the study is in a version prior to v8.8, the endpoint should raise as Antares-Craft doesn't handle such studies.
    res = client.get(f"/v1/studies/{internal_study_id}/craft")
    assert res.status_code == 422
    assert res.json()["description"] == "This method is only available for v8.8+ studies"

    # Upgrades the study in v8.8
    res = client.put(f"/v1/studies/{internal_study_id}/upgrade", params={"target_version": "8.8"})
    task_id = res.json()
    task = wait_task_completion(client, user_access_token, task_id, base_timeout=20)
    assert task.status == TaskStatus.COMPLETED

    res = client.get(f"/v1/studies/{internal_study_id}/craft")
    assert res.json() == {
        "areas": {
            "de": {
                "energyCostUnsupplied": 3000.0,
                "energyCostSpilled": 0.0,
                "nonDispatchPower": True,
                "dispatchHydroPower": True,
                "otherDispatchPower": True,
                "spreadUnsuppliedEnergyCost": 0.0,
                "spreadSpilledEnergyCost": 0.0,
                "filterSynthesis": "daily, monthly",
                "filterByYear": "hourly, weekly, annual",
                "adequacyPatchMode": "outside",
            },
            "es": {
                "energyCostUnsupplied": 3000.0,
                "energyCostSpilled": 0.0,
                "nonDispatchPower": True,
                "dispatchHydroPower": True,
                "otherDispatchPower": True,
                "spreadUnsuppliedEnergyCost": 0.0,
                "spreadSpilledEnergyCost": 0.0,
                "filterSynthesis": "daily, monthly",
                "filterByYear": "hourly, weekly, annual",
                "adequacyPatchMode": "outside",
            },
            "fr": {
                "energyCostUnsupplied": 3000.0,
                "energyCostSpilled": 0.0,
                "nonDispatchPower": True,
                "dispatchHydroPower": True,
                "otherDispatchPower": True,
                "spreadUnsuppliedEnergyCost": 0.0,
                "spreadSpilledEnergyCost": 0.0,
                "filterSynthesis": "",
                "filterByYear": "hourly",
                "adequacyPatchMode": "outside",
            },
            "it": {
                "energyCostUnsupplied": 3000.0,
                "energyCostSpilled": 0.0,
                "nonDispatchPower": True,
                "dispatchHydroPower": True,
                "otherDispatchPower": True,
                "spreadUnsuppliedEnergyCost": 0.0,
                "spreadSpilledEnergyCost": 0.0,
                "filterSynthesis": "",
                "filterByYear": "hourly",
                "adequacyPatchMode": "outside",
            },
        },
        "areas_ui": {
            "de": {
                "ui": {"x": 1, "y": 135, "color_r": 0, "color_g": 128, "color_b": 255, "layers": "0"},
                "layerX": {"0": 1},
                "layerY": {"0": 135},
                "layerColor": {"0": "0, 128, 255"},
            },
            "es": {
                "ui": {"x": -369, "y": -74, "color_r": 0, "color_g": 128, "color_b": 255, "layers": "0"},
                "layerX": {"0": -369},
                "layerY": {"0": -74},
                "layerColor": {"0": "0, 128, 255"},
            },
            "fr": {
                "ui": {"x": -309, "y": -1, "color_r": 0, "color_g": 128, "color_b": 255, "layers": "0"},
                "layerX": {"0": -309},
                "layerY": {"0": -1},
                "layerColor": {"0": "0, 128, 255"},
            },
            "it": {
                "ui": {"x": -99, "y": -55, "color_r": 0, "color_g": 128, "color_b": 255, "layers": "0"},
                "layerX": {"0": -99},
                "layerY": {"0": -55},
                "layerColor": {"0": "0, 128, 255"},
            },
        },
        "links": {
            "de / fr": {
                "area1": "de",
                "area2": "fr",
                "hurdlesCost": True,
                "loopFlow": False,
                "usePhaseShifter": False,
                "transmissionCapacities": "enabled",
                "assetType": "ac",
                "displayComments": True,
                "comments": "",
                "colorr": 112,
                "colorb": 112,
                "colorg": 112,
                "linkWidth": 1.0,
                "linkStyle": "plain",
                "filterSynthesis": "",
                "filterYearByYear": "hourly",
            },
            "es / fr": {
                "area1": "es",
                "area2": "fr",
                "hurdlesCost": True,
                "loopFlow": False,
                "usePhaseShifter": False,
                "transmissionCapacities": "enabled",
                "assetType": "ac",
                "displayComments": True,
                "comments": "",
                "colorr": 112,
                "colorb": 112,
                "colorg": 112,
                "linkWidth": 1.0,
                "linkStyle": "plain",
                "filterSynthesis": "",
                "filterYearByYear": "hourly",
            },
            "fr / it": {
                "area1": "fr",
                "area2": "it",
                "hurdlesCost": True,
                "loopFlow": False,
                "usePhaseShifter": False,
                "transmissionCapacities": "enabled",
                "assetType": "ac",
                "displayComments": True,
                "comments": "",
                "colorr": 112,
                "colorb": 112,
                "colorg": 112,
                "linkWidth": 1.0,
                "linkStyle": "plain",
                "filterSynthesis": "",
                "filterYearByYear": "hourly",
            },
        },
        "bcs": [],
        "renewable": {},
        "thermal": {
            "de / 01_solar": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 10.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 10.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "de / 02_wind_on": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 20.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 20.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "de / 03_wind_off": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 30.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 30.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "de / 04_res": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 40.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 40.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "de / 05_nuclear": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 50.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 50.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "de / 06_coal": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 60.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 60.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "de / 07_gas": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 70.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 70.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "de / 08_non-res": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 80.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 80.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "de / 09_hydro_pump": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 90.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 90.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "es / 01_solar": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 10.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 10.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "es / 02_wind_on": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 20.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 20.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "es / 03_wind_off": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 30.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 30.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "es / 04_res": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 40.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 40.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "es / 05_nuclear": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 50.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 50.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "es / 06_coal": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 60.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 60.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "es / 07_gas": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 70.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 70.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "es / 08_non-res": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 80.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 80.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "es / 09_hydro_pump": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 90.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 90.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "fr / 01_solar": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 10.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 10.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "fr / 02_wind_on": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 20.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 20.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "fr / 03_wind_off": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 30.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 30.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "fr / 04_res": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 40.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 40.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "fr / 05_nuclear": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 50.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 50.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "fr / 06_coal": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 60.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 60.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "fr / 07_gas": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 70.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 70.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "fr / 08_non-res": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 80.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 80.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "fr / 09_hydro_pump": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 90.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 90.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "it / 01_solar": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 10.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 10.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "it / 02_wind_on": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 20.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 20.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "it / 03_wind_off": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 30.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 30.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "it / 04_res": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 40.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 40.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "it / 05_nuclear": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 50.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 50.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "it / 06_coal": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 60.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 60.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "it / 07_gas": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 70.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 70.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "it / 08_non-res": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 80.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 80.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
            "it / 09_hydro_pump": {
                "unitCount": 1,
                "nominalCapacity": 1000000.0,
                "enabled": True,
                "group": "other 1",
                "genTs": "use global",
                "minStablePower": 0,
                "minUpTime": 1,
                "minDownTime": 1,
                "mustRun": False,
                "spinning": 0,
                "volatilityForced": 0,
                "volatilityPlanned": 0,
                "lawForced": "uniform",
                "lawPlanned": "uniform",
                "marginalCost": 90.0,
                "spreadCost": 0,
                "fixedCost": 0,
                "startupCost": 0,
                "marketBidCost": 90.0,
                "co2": 0,
                "nh3": 0,
                "so2": 0,
                "nox": 0,
                "pm25": 0,
                "pm5": 0,
                "pm10": 0,
                "nmvoc": 0,
                "op1": 0,
                "op2": 0,
                "op3": 0,
                "op4": 0,
                "op5": 0,
                "costGeneration": "SetManually",
                "efficiency": 100.0,
                "variableOMCost": 0.0,
            },
        },
        "sts": {},
        "sts_c": {},
        "hydro": {
            "de": {
                "managementOptions": {
                    "interDailyBreakdown": 1.0,
                    "intraDailyModulation": 2.0,
                    "interMonthlyBreakdown": 1.0,
                    "reservoir": False,
                    "reservoirCapacity": 0.0,
                    "followLoad": True,
                    "useWater": False,
                    "hardBounds": False,
                    "initializeReservoirDate": 0,
                    "useHeuristic": True,
                    "powerToLevel": False,
                    "useLeeway": False,
                    "leewayLow": 1.0,
                    "leewayUp": 1.0,
                    "pumpingEfficiency": 1.0,
                    "overflowSpilledCostDifference": None,
                },
                "inflowStructure": {"interMonthlyCorrelation": 0.5},
            },
            "es": {
                "managementOptions": {
                    "interDailyBreakdown": 1.0,
                    "intraDailyModulation": 2.0,
                    "interMonthlyBreakdown": 1.0,
                    "reservoir": False,
                    "reservoirCapacity": 0.0,
                    "followLoad": True,
                    "useWater": False,
                    "hardBounds": False,
                    "initializeReservoirDate": 0,
                    "useHeuristic": True,
                    "powerToLevel": False,
                    "useLeeway": False,
                    "leewayLow": 1.0,
                    "leewayUp": 1.0,
                    "pumpingEfficiency": 1.0,
                    "overflowSpilledCostDifference": None,
                },
                "inflowStructure": {"interMonthlyCorrelation": 0.5},
            },
            "fr": {
                "managementOptions": {
                    "interDailyBreakdown": 1.0,
                    "intraDailyModulation": 2.0,
                    "interMonthlyBreakdown": 1.0,
                    "reservoir": False,
                    "reservoirCapacity": 0.0,
                    "followLoad": True,
                    "useWater": False,
                    "hardBounds": False,
                    "initializeReservoirDate": 0,
                    "useHeuristic": True,
                    "powerToLevel": False,
                    "useLeeway": False,
                    "leewayLow": 1.0,
                    "leewayUp": 1.0,
                    "pumpingEfficiency": 1.0,
                    "overflowSpilledCostDifference": None,
                },
                "inflowStructure": {"interMonthlyCorrelation": 0.5},
            },
            "it": {
                "managementOptions": {
                    "interDailyBreakdown": 1.0,
                    "intraDailyModulation": 2.0,
                    "interMonthlyBreakdown": 1.0,
                    "reservoir": False,
                    "reservoirCapacity": 0.0,
                    "followLoad": True,
                    "useWater": False,
                    "hardBounds": False,
                    "initializeReservoirDate": 0,
                    "useHeuristic": True,
                    "powerToLevel": False,
                    "useLeeway": False,
                    "leewayLow": 1.0,
                    "leewayUp": 1.0,
                    "pumpingEfficiency": 1.0,
                    "overflowSpilledCostDifference": None,
                },
                "inflowStructure": {"interMonthlyCorrelation": 0.5},
            },
        },
        "xp_settings": {
            "master": "integer",
            "uc_type": "expansion_fast",
            "optimality_gap": 3.0,
            "relative_gap": 1e-06,
            "relaxed_optimality_gap": 1e-05,
            "max_iteration": 1000,
            "solver": "Xpress",
            "log_level": 0,
            "separation_parameter": 0.5,
            "batch_size": 96,
            "yearly-weights": "",
            "additional-constraints": "",
            "timelimit": 1000000000000,
            "sensitivity_config": {"epsilon": 0.0, "projection": [], "capex": False},
        },
        "ts_config": {"thermal": {"number": 1}},
        "general_config": {
            "mode": "Adequacy",
            "firstDay": 1,
            "lastDay": 7,
            "horizon": "2030",
            "firstMonth": "january",
            "firstWeekDay": "Monday",
            "firstJanuary": "Monday",
            "leapYear": False,
            "nbYears": 1,
            "buildingMode": "Custom",
            "selectionMode": True,
            "yearByYear": False,
            "simulationSynthesis": True,
            "mcScenario": True,
            "filtering": None,
            "geographicTrimming": True,
            "thematicTrimming": False,
        },
        "adv_config": {
            "accuracyOnCorrelation": "",
            "powerFluctuations": "free modulations",
            "sheddingPolicy": "shave peaks",
            "hydroPricingMode": "fast",
            "hydroHeuristicPolicy": "accommodate rule curves",
            "unitCommitmentMode": "fast",
            "numberOfCoresMode": "maximum",
            "dayAheadReserveManagement": "global",
            "renewableGenerationModelling": "aggregated",
            "seedTsgenWind": 5489,
            "seedTsgenLoad": 1005489,
            "seedTsgenHydro": 2005489,
            "seedTsgenThermal": 3005489,
            "seedTsgenSolar": 4005489,
            "seedTsnumbers": 5005489,
            "seedUnsuppliedEnergyCosts": 6005489,
            "seedSpilledEnergyCosts": 7005489,
            "seedThermalCosts": 8005489,
            "seedHydroCosts": 9005489,
            "seedInitialReservoirLevels": 10005489,
            "initialReservoirLevels": "cold start",
            "accurateShavePeaksIncludeShortTermStorage": None,
        },
        "playlist": {"years": {"1": {"status": True, "weight": 1}}},
        "thematic_config": {
            "ovCost": True,
            "opCost": True,
            "mrgPrice": True,
            "co2Emis": True,
            "dtgByPlant": True,
            "balance": True,
            "rowBal": True,
            "psp": True,
            "miscNdg": True,
            "load": True,
            "hRor": True,
            "wind": True,
            "hStor": True,
            "hPump": True,
            "hLev": True,
            "hInfl": True,
            "hOvfl": True,
            "hVal": True,
            "hCost": True,
            "unspEnrg": True,
            "spilEnrg": True,
            "lold": True,
            "lolp": True,
            "avlDtg": True,
            "dtgMrg": True,
            "maxMrg": True,
            "npCost": True,
            "npCostByPlant": True,
            "nodu": True,
            "noduByPlant": True,
            "flowLin": True,
            "ucapLin": True,
            "loopFlow": True,
            "flowQuad": True,
            "congFeeAlg": True,
            "congFeeAbs": True,
            "margCost": True,
            "congProbPlus": True,
            "congProbMinus": True,
            "hurdleCost": True,
            "resGenerationByPlant": True,
            "dens": True,
            "profitByPlant": True,
            "bcMargCost": True,
            "stsInjByPlant": True,
            "stsWithdrawalByPlant": True,
            "stsLvlByPlant": True,
            "stsCashflowByCluster": True,
            "npcapHours": True,
            "stsByGroup": None,
            "dispatchGen": None,
            "renewableGen": None,
            "pspOpenInjection": True,
            "pspOpenWithdrawal": True,
            "pspOpenLevel": True,
            "pspClosedInjection": True,
            "pspClosedWithdrawal": True,
            "pspClosedLevel": True,
            "pondageInjection": True,
            "pondageWithdrawal": True,
            "pondageLevel": True,
            "batteryInjection": True,
            "batteryWithdrawal": True,
            "batteryLevel": True,
            "other1Injection": True,
            "other1Withdrawal": True,
            "other1Level": True,
            "other2Injection": True,
            "other2Withdrawal": True,
            "other2Level": True,
            "other3Injection": True,
            "other3Withdrawal": True,
            "other3Level": True,
            "other4Injection": True,
            "other4Withdrawal": True,
            "other4Level": True,
            "other5Injection": True,
            "other5Withdrawal": True,
            "other5Level": True,
            "miscDtg2": True,
            "miscDtg3": True,
            "miscDtg4": True,
            "windOffshore": True,
            "windOnshore": True,
            "solarConcrt": True,
            "solarPv": True,
            "solarRooft": True,
            "renw1": True,
            "renw2": True,
            "renw3": True,
            "renw4": True,
            "solar": True,
            "nuclear": True,
            "lignite": True,
            "coal": True,
            "gas": True,
            "oil": True,
            "mixFuel": True,
            "miscDtg": True,
        },
        "opt_config": {
            "bindingConstraints": True,
            "hurdleCosts": True,
            "transmissionCapacities": "local-values",
            "thermalClustersMinStablePower": True,
            "thermalClustersMinUdTime": True,
            "dayAheadReserve": True,
            "primaryReserve": True,
            "strategicReserve": True,
            "spinningReserve": True,
            "exportMps": False,
            "unfeasibleProblemBehavior": "error-verbose",
            "simplexOptimizationRange": "week",
        },
        "adequacy_config": {
            "enableAdequacyPatch": False,
            "ntcFromPhysicalAreasOutToPhysicalAreasInAdequacyPatch": True,
            "priceTakingOrder": "DENS",
            "includeHurdleCostCsr": False,
            "checkCsrCostFunction": False,
            "thresholdInitiateCurtailmentSharingRule": 1.0,
            "thresholdDisplayLocalMatchingRuleViolations": 0.0,
            "thresholdCsrVariableBoundsRelaxation": 7,
            "ntcBetweenPhysicalAreasOutAdequacyPatch": True,
            "redispatch": None,
        },
        "version": "8.8",
        "name": "STA-mini",
        "path": ANY,
        "outputs": {
            "20201014-1422eco-hello": {
                "name": "hello",
                "date": "20201014-1422",
                "mode": "Economy",
                "nbyears": 1,
                "synthesis": True,
                "by_year": True,
                "error": False,
                "playlist": [1],
                "archived": False,
                "xpansion": "",
            },
            "20201014-1425eco-goodbye": {
                "name": "goodbye",
                "date": "20201014-1425",
                "mode": "Economy",
                "nbyears": 2,
                "synthesis": True,
                "by_year": True,
                "error": False,
                "playlist": [1, 2],
                "archived": False,
                "xpansion": "",
            },
            "20201014-1427eco": {
                "name": "",
                "date": "20201014-1427",
                "mode": "Economy",
                "nbyears": 1,
                "synthesis": True,
                "by_year": False,
                "error": False,
                "playlist": [1],
                "archived": False,
                "xpansion": "",
            },
            "20201014-1430adq": {
                "name": "",
                "date": "20201014-1430",
                "mode": "Adequacy",
                "nbyears": 1,
                "synthesis": True,
                "by_year": False,
                "error": False,
                "playlist": [1],
                "archived": False,
                "xpansion": "",
            },
            "20201014-1430adq-2": {
                "name": "2",
                "date": "20201014-1430",
                "mode": "Adequacy",
                "nbyears": 1,
                "synthesis": True,
                "by_year": False,
                "error": False,
                "playlist": [1],
                "archived": True,
                "xpansion": "",
            },
            "20241807-1540eco-extra-outputs": {
                "name": "extra-outputs",
                "date": "20241807-1540",
                "mode": "Economy",
                "nbyears": 1,
                "synthesis": True,
                "by_year": True,
                "error": False,
                "playlist": [],
                "archived": False,
                "xpansion": "",
            },
        },
        "xp_cdt": [],
    }
