# Copyright (c) 2026, RTE (https://www.rte-france.com)
#
# See AUTHORS.txt
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0
#
# This file is part of the Antares project.
import numpy as np
import pytest
from starlette.testclient import TestClient


def test_get_raw_output_matrix(admin_client: TestClient, internal_study_id: str) -> None:
    client = admin_client

    res = client.get(
        f"/v1/studies/{internal_study_id}/raw",
        params={"path": "output/20201014-1422eco-hello/economy/mc-ind/00001/areas/es/values-annual"},
    )

    nan = pytest.approx(np.nan, nan_ok=True)

    assert res.json() == {
        "columns": [
            ["OV. COST", "Euro", ""],
            ["OP. COST", "Euro", ""],
            ["MRG. PRICE", "Euro", ""],
            ["CO2 EMIS.", "Tons", ""],
            ["BALANCE", "MWh", ""],
            ["ROW BAL.", "MWh", ""],
            ["PSP", "MWh", ""],
            ["MISC. NDG", "MWh", ""],
            ["LOAD", "MWh", ""],
            ["H. ROR", "MWh", ""],
            ["WIND", "MWh", ""],
            ["SOLAR", "MWh", ""],
            ["NUCLEAR", "MWh", ""],
            ["LIGNITE", "MWh", ""],
            ["COAL", "MWh", ""],
            ["GAS", "MWh", ""],
            ["OIL", "MWh", ""],
            ["MIX. FUEL", "MWh", ""],
            ["MISC. DTG", "MWh", ""],
            ["H. STOR", "MWh", ""],
            ["H. PUMP", "MWh", ""],
            ["H. LEV", "%", ""],
            ["H. INFL", "MWh", ""],
            ["H. OVFL", "%", ""],
            ["H. VAL", "Euro/MWh", ""],
            ["H. COST", "Euro", ""],
            ["UNSP. ENRG", "MWh", ""],
            ["SPIL. ENRG", "MWh", ""],
            ["LOLD", "Hours", ""],
            ["LOLP", "%", ""],
            ["AVL DTG", "MWh", ""],
            ["DTG MRG", "MWh", ""],
            ["MAX MRG", "MWh", ""],
            ["NP COST", "Euro", ""],
            ["NODU", " ", ""],
        ],
        "data": [
            [
                46452000.0,
                46452000.0,
                47.14,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                1402800.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                1402800.0,
                0.0,
                0.0,
                nan,
                0.0,
                nan,
                nan,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                3024000.0,
                1621200.0,
                1621200.0,
                0.0,
                783.0,
            ]
        ],
    }

    res = client.get(
        f"/v1/studies/{internal_study_id}/raw",
        params={"path": "output/20201014-1422eco-hello/economy/mc-ind/00001/areas/es/values-daily"},
    )

    assert res.status_code == 404

    res = client.get(
        f"/v1/studies/{internal_study_id}/raw",
        params={"path": "output/20201014-1422eco-hello/economy/mc-all/areas/es/values-monthly"},
    )

    assert res.json() == {
        "columns": [
            ["OV. COST", "Euro", "EXP"],
            ["OP. COST", "Euro", "EXP"],
            ["OP. COST", "Euro", "std"],
            ["OP. COST", "Euro", "min"],
            ["OP. COST", "Euro", "max"],
            ["MRG. PRICE", "Euro", "EXP"],
            ["MRG. PRICE", "Euro", "std"],
            ["MRG. PRICE", "Euro", "min"],
            ["MRG. PRICE", "Euro", "max"],
            ["CO2 EMIS.", "Tons", "EXP"],
            ["BALANCE", "MWh", "EXP"],
            ["BALANCE", "MWh", "std"],
            ["BALANCE", "MWh", "min"],
            ["BALANCE", "MWh", "max"],
            ["ROW BAL.", "MWh", "values"],
            ["PSP", "MWh", "EXP"],
            ["MISC. NDG", "MWh", "EXP"],
            ["LOAD", "MWh", "EXP"],
            ["LOAD", "MWh", "std"],
            ["LOAD", "MWh", "min"],
            ["LOAD", "MWh", "max"],
            ["H. ROR", "MWh", "EXP"],
            ["H. ROR", "MWh", "std"],
            ["H. ROR", "MWh", "min"],
            ["H. ROR", "MWh", "max"],
            ["WIND", "MWh", "EXP"],
            ["WIND", "MWh", "std"],
            ["WIND", "MWh", "min"],
            ["WIND", "MWh", "max"],
            ["SOLAR", "MWh", "EXP"],
            ["SOLAR", "MWh", "std"],
            ["SOLAR", "MWh", "min"],
            ["SOLAR", "MWh", "max"],
            ["NUCLEAR", "MWh", "EXP"],
            ["NUCLEAR", "MWh", "std"],
            ["NUCLEAR", "MWh", "min"],
            ["NUCLEAR", "MWh", "max"],
            ["LIGNITE", "MWh", "EXP"],
            ["LIGNITE", "MWh", "std"],
            ["LIGNITE", "MWh", "min"],
            ["LIGNITE", "MWh", "max"],
            ["COAL", "MWh", "EXP"],
            ["COAL", "MWh", "std"],
            ["COAL", "MWh", "min"],
            ["COAL", "MWh", "max"],
            ["GAS", "MWh", "EXP"],
            ["GAS", "MWh", "std"],
            ["GAS", "MWh", "min"],
            ["GAS", "MWh", "max"],
            ["OIL", "MWh", "EXP"],
            ["OIL", "MWh", "std"],
            ["OIL", "MWh", "min"],
            ["OIL", "MWh", "max"],
            ["MIX. FUEL", "MWh", "EXP"],
            ["MIX. FUEL", "MWh", "std"],
            ["MIX. FUEL", "MWh", "min"],
            ["MIX. FUEL", "MWh", "max"],
            ["MISC. DTG", "MWh", "EXP"],
            ["MISC. DTG", "MWh", "std"],
            ["MISC. DTG", "MWh", "min"],
            ["MISC. DTG", "MWh", "max"],
            ["H. STOR", "MWh", "EXP"],
            ["H. STOR", "MWh", "std"],
            ["H. STOR", "MWh", "min"],
            ["H. STOR", "MWh", "max"],
            ["H. PUMP", "MWh", "EXP"],
            ["H. PUMP", "MWh", "std"],
            ["H. PUMP", "MWh", "min"],
            ["H. PUMP", "MWh", "max"],
            ["H. LEV", "%", "EXP"],
            ["H. LEV", "%", "std"],
            ["H. LEV", "%", "min"],
            ["H. LEV", "%", "max"],
            ["H. INFL", "MWh", "EXP"],
            ["H. INFL", "MWh", "std"],
            ["H. INFL", "MWh", "min"],
            ["H. INFL", "MWh", "max"],
            ["H. OVFL", "%", "EXP"],
            ["H. OVFL", "%", "std"],
            ["H. OVFL", "%", "min"],
            ["H. OVFL", "%", "max"],
            ["H. VAL", "Euro/MWh", "EXP"],
            ["H. VAL", "Euro/MWh", "std"],
            ["H. VAL", "Euro/MWh", "min"],
            ["H. VAL", "Euro/MWh", "max"],
            ["H. COST", "Euro", "EXP"],
            ["H. COST", "Euro", "std"],
            ["H. COST", "Euro", "min"],
            ["H. COST", "Euro", "max"],
            ["UNSP. ENRG", "MWh", "EXP"],
            ["UNSP. ENRG", "MWh", "std"],
            ["UNSP. ENRG", "MWh", "min"],
            ["UNSP. ENRG", "MWh", "max"],
            ["SPIL. ENRG", "MWh", "EXP"],
            ["SPIL. ENRG", "MWh", "std"],
            ["SPIL. ENRG", "MWh", "min"],
            ["SPIL. ENRG", "MWh", "max"],
            ["LOLD", "Hours", "EXP"],
            ["LOLD", "Hours", "std"],
            ["LOLD", "Hours", "min"],
            ["LOLD", "Hours", "max"],
            ["LOLP", "%", "values"],
            ["AVL DTG", "MWh", "EXP"],
            ["AVL DTG", "MWh", "std"],
            ["AVL DTG", "MWh", "min"],
            ["AVL DTG", "MWh", "max"],
            ["DTG MRG", "MWh", "EXP"],
            ["DTG MRG", "MWh", "std"],
            ["DTG MRG", "MWh", "min"],
            ["DTG MRG", "MWh", "max"],
            ["MAX MRG", "MWh", "EXP"],
            ["MAX MRG", "MWh", "std"],
            ["MAX MRG", "MWh", "min"],
            ["MAX MRG", "MWh", "max"],
            ["NP COST", "Euro", "EXP"],
            ["NP COST", "Euro", "std"],
            ["NP COST", "Euro", "min"],
            ["NP COST", "Euro", "max"],
            ["NODU", " ", "EXP"],
            ["NODU", " ", "std"],
            ["NODU", " ", "min"],
            ["NODU", " ", "max"],
        ],
        "data": [
            [
                46452000.0,
                46452000.0,
                0.0,
                46452000.0,
                46452000.0,
                47.14,
                0.0,
                47.14,
                47.14,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                1402800.0,
                0.0,
                1402800.0,
                1402800.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                1402800.0,
                0.0,
                1402800.0,
                1402800.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                nan,
                nan,
                nan,
                nan,
                0.0,
                0.0,
                0.0,
                0.0,
                nan,
                nan,
                nan,
                nan,
                nan,
                nan,
                nan,
                nan,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                3024000.0,
                0.0,
                3024000.0,
                3024000.0,
                1621200.0,
                0.0,
                1621200.0,
                1621200.0,
                1621200.0,
                0.0,
                1621200.0,
                1621200.0,
                0.0,
                0.0,
                0.0,
                0.0,
                783.0,
                0.0,
                783.0,
                783.0,
            ]
        ],
    }

    res = client.get(
        f"/v1/studies/{internal_study_id}/raw",
        params={"path": "output/20201014-1422eco-hello/economy/mc-all/areas/es/values-annual"},
    )

    assert res.status_code == 404
