security:
  disabled: true # If False, when launching the app, the user needs to identy himself, else it's not needed (default False)
  jwt:
    key: super-secret # JWT secret key for authentication (default "")
  login:
    admin:
      pwd: admin # Admin user's password (default "")
  external_auth:
    url: "" # External authentication URL , "" for local authentication (default None)
    default_group_role: 10 # Default user role for external authentication (default 10 which means READER)
    add_ext_groups: false # Whether to add external groups to user roles (default False)
    # group_mapping: Groups with their names and ids (default {})


db:
  url: "sqlite:///database.db" # Database URL (SQLite in this case), other example : "postgresql://path_to_db"

  # admin_url: The URL you can use to directly access your database (default None)
  # pool_use_null: If true, the Pool does not pool connections (default False and should stay like this)
  # db_connect_timeout: Database timeout to create the connection (default 10)
  # pool_recycle: Prevents the pool from using a particular connection that has passed a certain time in seconds (value often used: 3600) (default None), not used for SQLite
  # pool_size: Maximum number of permanent connections to keep (default 5), not used for SQLite
  # pool_use_lifo: Should Database use Last-in First-out method (default False), not used for SQLite
  # pool_pre_ping: (default False), not used for SQLite
  # pool_max_overflow: Temporarily exceeds the set pool_size if no connections are available (default 10), not used for SQLite


storage:
  tmp_dir: ./tmp # Temporary directory for storing temporary files
  matrixstore: ./matrices # Directory for matrix storage
  archive_dir: ./examples/archives # Directory for archived studies
  allow_deletion: false  # Indicates if studies found in non-default workspace can be deleted by the application (default False)
  workspaces:
  # If a directory is to be ignored by the watcher, place a file named AW_NO_SCAN inside
    default:
      path: ./examples/internal_studies/ # Path to the default workspace which is also the one containing every managed study
    studies:
      path: ./examples/studies/  # Path to the "studies" workspace
      # filter_in: If a folder does not contain a file with a name matching a regex in the list, it will not be scanned (default to ['.*'])
      # filter_out: If a folder contains any file with a name matching a regex in the list, it is not scanned (default to [])
      # groups: Group names corresponding to the path (default [])
    staging_studies:
      path: ./examples/staging_studies/  # Example of other workspaces that can be registered
  # matrix_gc_sleeping_time: # Time in seconds to sleep between two garbage collections (default 3600)
  # auto_archive_sleeping_time: Same as matrix_gc_sleeping_time for auto_archive (default 3600)
  # matrix_gc_dry_run:If True, matrices will never be removed. Else, the ones that are unused will (default False)
  # auto_archive_dry_run: Same as matrix_gc_dry_run for studies (default False)
  # auto_archive_threshold_days: If no one had access to a study for x days, it will be archived (default 60)
  # auto_archive_max_parallel: Max parallel archiving task taht can be performed (default 5)
  # watcher_lock: If False, it will scan whithout any delay (default  True)
  # watcher_lock_delay: Seconds delay between two scans(default 10)
  # download_default_expiration_timeout_minutes: Minutes before your study download will be cleared (default 1440 so 24 hours)


launcher:
  default: local # Default launcher configuration
  local:
    enable_nb_cores_detection: False  # Enable detection of available CPU cores on the machine (default False)
    binaries:
    # Binary paths for various versions of the launcher
      700: path/to/700
#  slurm:
#    local_workspace: /path/to/slurm_workspace  # Path to the local SLURM workspace
#    username: run-antares  # SLURM username
#    hostname: 10.134.248.111  # SLURM server hostname
#    port: 22  # SSH port for SLURM
#    private_key_file: /path/to/ssh_private_key  # SSH private key file
#    default_wait_time: 900  # Default wait time for SLURM jobs
#    default_time_limit: 172800  # Default time limit for SLURM jobs
#    enable_nb_cores_detection: False  # Enable detection of available CPU cores for SLURM
#    nb_cores:
#      min: 1  # Minimum number of CPU cores
#      default: 22  # Default number of CPU cores
#      max: 24  # Maximum number of CPU cores
#    default_json_db_name: launcher_db.json  # Default JSON database name for SLURM
#    slurm_script_path: /applis/antares/launchAntares.sh  # Path to the SLURM script (on distant server)
#    db_primary_key: name  # Primary key for the SLURM database
#    antares_versions_on_remote_server: #List of Antares versions available on the remote SLURM server
#      - "840"
#      - "850"


debug: false # Disable debugging (default False)

root_path: "api" # Root path for FastAPI (default "")

# cache:
#   checker_delay: Time in seconds to sleep before checking what needs to be remove from cache (default 0.2)

#tasks:
#  max_workers: Number of threads for Tasks in the ThreadPoolExecutor (default 5)
#  remote_workers: (default [])
server:
  worker_threadpool_size: 12 # Number of threads of the Server in the ThreadPoolExecutor (default 5)
  services: # Services to enable (default [])
    - watcher

logging:
  level: INFO  # Logging level (INFO, DEBUG, etc.) (Default INFO)
  logfile: ./tmp/antarest.log  # Path to the application log file (Default None)
  #json: If True, logging format will be "json", else it is "console" (default False)

# Uncomment these lines to use Redis as a backend for the eventbus
# It is required to use Redis when using this application on multiple workers in a preforked model like Gunicorn for instance
#redis:
#  host: localhost
#  port: 6379
#  password: (default None)


# Questions sur: - max_workers *2
# - watcher lock
# - services
# - remote workers (+ ex. du service _timeseries_generator)
