name: changelog
on:
  push:
    branches:
      - 'changelog'
jobs:
  generate-changelog:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: BobAnkh/auto-generate-changelog@v1
      with:
        REPO_NAME: 'AntaRest'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PATH: '../../resources/deploy/CHANGELOG.md'
        BRANCH: 'changelog'
        COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
        TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation'
