name: commitlint

on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo 
        uses: actions/checkout@v4
      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v5
