name: license-header
on:
  push:
    branches:
      - "**"

jobs:
  check-license-headers:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: 3.14
      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv pip install --system click
      - name: Check licenses header
        run: |
          python license_checker_and_adder.py --path=../antarest/ --action=check-strict
          python license_checker_and_adder.py --path=../tests/  --action=check-strict
          python license_checker_and_adder.py --path=../webapp/src  --action=check-strict
        working-directory: scripts
