name: license-header
on:
  push:
    branches:
      - "**"

jobs:
  check-license-headers:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install click
      - name: Check licenses header
        run: |
          python license_checker_and_adder.py --path=../antarest/ --action=check-strict
          python license_checker_and_adder.py --path=../tests/  --action=check-strict
          python license_checker_and_adder.py --path=../webapp/src  --action=check-strict
        working-directory: scripts
