name: main
on:
  push:
    branches:
      - "**"

jobs:
  python-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install dependencies
        run: uv sync --frozen --extra desktop --compile-bytecode
      - name: Check format (ruff)
        run: |
          uv run --frozen ruff check antarest/ tests/
          uv run --frozen ruff format --check antarest/ tests/
      - name: Check Typing (mypy)
        run: uv run --frozen mypy --install-types --non-interactive

  python-test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 9
      matrix:
        os: [windows-latest, ubuntu-22.04]

    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install dependencies
        run: uv sync --frozen --compile-bytecode
      - name: Test with pytest
        run: uv run --frozen pytest -s tests/integration/raw_studies_blueprint/test_download_matrices.py
      - name: Archive code coverage results
        if: matrix.os == 'ubuntu-22.04'
        uses: actions/upload-artifact@v7
        with:
          name: python-code-coverage-report
          path: coverage.xml
