name: pr-title
on:
    pull_request:
      types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  pr-title-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: npm install @commitlint/config-conventional@16.0.0
    - uses: JulienKode/pull-request-name-linter-action@v0.5.0
