name: pr-title
on:
    pull_request:
      types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  pr-title-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - name: Install Dependencies
      run: npm install @commitlint/config-conventional@16.0.0
    - uses: JulienKode/pull-request-name-linter-action@8c05fb989d9f156ce61e33754f9802c9d3cffa58 # v0.5.0
