name: updatedocs
on:
  push:
    branches:
      - 'dev' 
      - 'changelog'


jobs:
  binary:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
        run: |
          git log -1 HEAD --format=%H > .\resources\commit_id
          pyinstaller -F antarest\worker\archive_worker_service.py -n AntaresWebWorker --add-data ".\resources;.\resources"
      - name: Update package version
        run: bash ./update_version.sh
        working-directory: scripts
      - name: update package version on 2-deploy.md
        run: sed -E -i 's/v[0-7].[0-9].[0-9]/v${{VERSION}}/g' 2-DEPLOY.md   
      - name: update changelog docs files
        run: |
          bash ./../../scripts/generate-changelogdocs.sh > ../../docs/CHANGELOG.md