name: worker
on:
  push:
    branches:
      - "master"
      - "worker/**"

jobs:
  binary:
    runs-on: windows-latest

    steps:
      - name: 🐙 Checkout GitHub repo (+ download lfs dependencies)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🐍 Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: 🔧 Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: 🐍 Install dependencies
        run: uv sync --frozen --extra desktop --extra windows --compile-bytecode

      - name: 📦 Packaging AntaresWebWorker
        run: bash ./package_worker.sh
        working-directory: scripts

      - name: 🚀 Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: AntaresWebWorker
          path: dist/AntaresWebWorker.exe
